<?php

/********************************************
*             Tõlkija: Dominus              *
*              dominus@hot.ee               *
*        http://www.zone.ee/dominus         *
*********************************************/

//general
$l_yes 			 = "Jah";
$l_no			 = "Ei";
$l_here			 = "siia";
$l_submit		 = "Salvesta";
$l_reset		 = "T&uuml;hista";
$l_all			 = "K&otilde;ik";

$l_ore			 = "Maak";
$l_commodities      = "<B>Kaubavarud</B>";
$l_organics		 = "Orgaanika";
$l_goods		 = "Tarbekaup";
$l_energy		 = "Energia";
$l_colonists		 = "Kolonistid";
$l_credits 		 = "Raha";
$l_units		 = "&uuml;hikut ";
$l_special		 = "Keskjaam";

$l_cargo		 = "Laadung";
$l_fighters		 = "H&auml;vitajad ";
$l_mines		 = "Miinid ";
$l_torps		 = "Torpeedod";

$l_none			 = "Pole";
$l_unnamed		 = "Nimetu";
$l_name			 = "Nimi";
$l_unowned		 = "Omanikuta";
$l_unknown		 = "Teadmata";
$l_clickme 		 = "Vajuta siia";
$l_player  		 = "M&auml;ngija";
$l_ship			 = "Laev";
$l_ships		 = "Laevad";
$l_set			 = "m&auml;&auml;ra";
$l_realspace		 = "Avakosmos";
$l_armourpts		 = "Soomusepunktid";
$l_links		 = "Lingid";

// main.php

$l_main_title 		 = "Peamen&uuml;&uuml;";
$l_main_warpto = "Varbi";
$l_main_other = "Muu";
$l_main_shipyard = "Sisene <a href=shipyard.php>Laevatehasesse</a>";

$l_traderoutes		 = "Kaubateed";
$l_trade_control	 = "M&auml;rkmik";

$l_youhave 		 = "Sulle on ";
$l_turns_used		 = "K&auml;ike kasutatud: ";
$l_turns_have		 = "K&auml;ike kasutamata: ";
$l_score		 = "Skoor: ";
$l_sector		 = "Sektor";
$l_help			 = "Abi";
$l_faq		         = "KKK";
$l_feedback		 = "Tagasiside";
$l_forums		 = "Foorumid";
$l_logout		 = "Logi v&auml;lja";

$l_commands		 = "Men&uuml;&uuml;";
$l_command_no		 = "K&auml;sk ei ole kasutatav.";
$l_devices		 = "Seadmed";
$l_planets		 = "Planeedid";
$l_log			 = "Logiraamat";
$l_sector_def		 = "Sektori kaitsed";
$l_defense		 = "<B>Kaitses&uuml;steemid</B>";
$l_read_msg		 = "Loe teateid";
$l_send_msg		 = "Saada teateid";
$l_rankings		 = "Edetabel";
$l_teams		 = "Liidud";
$l_ohno			 = "Eneseh&auml;vitus";
$l_options		 = "Seaded";
$l_navcomp		 = "Pardakompuuter";

$l_incompletemove 	 = "Sa ei ole l&otilde;petanud oma eelmist liikumist.";
$l_clicktocontinue	 = "Vajuta siia, et j&auml;tkata";
$l_toplanetmenu   	 = "et minna planeedi men&uuml;&uuml;sse.";
$l_nonexistant_pl	 = "Mitteeksisteerival planeedil???";
$l_abord		 = ", laeval ";
$l_messages_wait	 = " lugemata teadet.";

$l_no_warplink		 = "Varp koridore ei ole";
$l_scan			 = "vaatle";
$l_fullscan		 = "T&auml;isvaatlus";

$l_port			 = "Sadam";
$l_tradingport		 = "Kaubasadam";
$l_planet_in_sec	 = "Planeedid sektoris ";
$l_ships_in_sec		 = "Teised laevad sektoris ";
$l_sector_0		 = "Sol-is (Sektor 0) on liiga tihe liiklus, et laevu eristada.";

// report.php

$l_report_title		 = "Laeva raport";

$l_level		 = "Tase";

$l_ship_levels		 = "Laeva osade tasemed";
$l_hull			 = "Kere";
$l_engines		 = "Mootorid";
$l_power		 = "Akud";
$l_computer		 = "Pardaarvuti";
$l_sensors		 = "Sensorid";
$l_armour		 = "Soomus";
$l_shields		 = "Energiakilp";
$l_beams		 = "Laserid";
$l_torp_launch	         = "Torpeedoheitjad";
$l_cloak		 = "Radarisegaja";
$l_holds		 = "Laadung";
$l_deflect		 = "Miinit&otilde;rjujad";
$l_ewd			 = "H&auml;daabi varp";
$l_shipavg                   = "Keskmine tehniline tase";

$l_arm_weap		 = "Soomus ja relvastus";
$l_beacons		 = "Majakad";
$l_warpedit		 = "Varbimuundurid";
$l_genesis		 = "Mateeriatorpeedod";
$l_escape_pod		 = "P&auml;&auml;stekapsel";
$l_fuel_scoop		 = "Generaator";
$l_total_cargo  = "Kogulaadung";
$l_installed = "Pardal";


// device.php

$l_device_title		 = "Seadmed";

$l_device_expl		 = "Sinu laeval on j&auml;rgmised seadmed (kliki lingil, et seadet kasutada):";
$l_device		 = "Seade";
$l_qty			 = "Hulk";
$l_usage		 = "Kasutus";
$l_manual		 = "K&auml;sitsi";
$l_automatic		 = "Automaatne";

// port.php port2.php

$l_trade		 = "Kauple";
$l_title_port		 = "Sadamas kauplemine";
$l_title_trade		 = "Kauplemine";
$l_sector_war		 = "S&otilde;jaembargo";
$l_war_info		 = "Siin sektoris k&auml;ib s&otilde;da. Sa ei suutnud j&otilde;uda sadamani, kuna Sind segasid vaenutsevad v&auml;ed.";
$l_no_trade		 = "Kauplemine keelatud";
$l_no_trade_out		 = "Selles sadamas ei ole v&otilde;&otilde;rastel kauplemine lubatud";
$l_no_trade_info	 = "Selles sadamas ei ole kauplemine lubatud";
$l_buying		 = "Ostab";
$l_selling		 = "M&uuml;&uuml;b";
$l_commodity		 = "Kaup";
$l_amount		 = "Kogus";
$l_price		 = "Hind";
$l_buy			 = "Osta";
$l_sell			 = "M&uuml;&uuml;";
$l_trade_st_info	 = "Sul on [free_holds] &uuml;hikut vaba ruumi, Sa saad juurde osta [free_power] &uuml;hikut energiat ja Sul on [credits] raha.";
$l_special_port		 = "Keskjaam";
$l_no_credits		 = "Sul ei ole piisavalt raha";
$l_creds_to_spend	 = "Sul on [credits] raha kulutamiseks.";
$l_cost			 = "Hind";
$l_avail		 = "Saadaval";
$l_profit		 = "Kasum";
$l_current		 = "Hetkel";
$l_current_qty		 = "Hetkekogus";
$l_max			 = "Max";
$l_ifyouneedmore	 = "Kui Sa vajad rohkem, siis siin on [igb] ";
$l_ifyouneedplan	 = "Siin on planeedi";
$l_igb_term		 = "IGB pangaterminal";
$l_upgrade		 = "Arenda?";
$l_unlimited		 = "Piiramatu";
$l_full			 = "T&auml;is";
$l_equipped		 = "Pardal";
$l_n_a			 = "-";
$l_item			 = "Kaup";
$l_totalcost		 = "Kogumaksumus";
$l_would_dump	         = "Kui Sa soovid k&otilde;ik kolonistid Maale tagasi saata, vajuta ";
$l_noport		 = "Siin ei ole kaubasadamat!";
$l_trade_turnneed	 = "Sul peab olema v&auml;hemalt &uuml;ks vaba k&auml;ik, et kaubelda sadamas v&otilde;i planeedil.";
$l_returnto_port         = " Vajuta <A HREF=port.php>siia</A>, et minna sadama men&uuml;&uuml;sse.";
$l_notenough_cargo	 = "Sul ei ole piisavalt vaba ruumi, et l&otilde;petada tehingut.";
$l_notenough_power	 = "Sul ei ole piisavalt ruumi energiale, et l&otilde;petada tehingut.";
$l_notenough_credits	 = "Sul ei ole piisavalt raha, et l&otilde;petada tehingut.";
$l_notenough_turns	 = "Sul ei ole piisavalt k&auml;ike, et l&otilde;petada tehingut.";
$l_notenough_ore	 = "Sul ei ole piisavalt maaki, et l&otilde;petada tehingut.";
$l_notenough_goods	 = "Sul ei ole piisavalt tarbekaupa, et l&otilde;petada tehingut.";
$l_notenough_energy	 = "Sul ei ole piisavalt energiat, et l&otilde;petada tehingut.";
$l_notenough_organics	 = "Sul ei ole piisavalt orgaanikat, et l&otilde;petada tehingut.";
$l_exceed_organics	 = "Orgaanika kogus &uuml;letab varu/n&otilde;udmist.  ";
$l_exceed_ore            = "Maagi kogus &uuml;letab varu/n&otilde;udmist.  ";
$l_exceed_energy         = "Energia kogus &uuml;letab varu/n&otilde;udmist.  ";
$l_exceed_goods          = "Tarbekauba kogus &uuml;letab varu/n&otilde;udmist.  ";
$l_trade_result		 = "Kauplemise tulemused";
$l_traded_ore		 = "Kaubeldud maak";
$l_traded_goods		 = "Kaubeldud tarbekaup";
$l_traded_organics	 = "Kaubeldud orgaanika";
$l_traded_energy	 = "Kaubeldud energia";
$l_trade_complete	 = "Kauplemine l&otilde;petatud";
$l_trade_upgraded = "Uuendatud tasemele ";
$l_trade_added = "lisatud";
$l_trade_installed = "installeeritud";


// planet.php planet2.php planet3.php
$l_planet_title		 = "Planeedi men&uuml;&uuml;";
$l_planet_none		 = "Sa ei ole planeediga samas sektoris, seega ei saa Sa sellega tegeleda.";
$l_planet_capture1	 = "h&otilde;ivata"; // thats the link's text
$l_planet_capture2	 = "Sa v&otilde;id planeedi [capture] v&otilde;i lihtsalt kaitseta j&auml;tta.";
$l_planet_unowned	 = "See planeet on omanikuta";
$l_planet_unnamed        = "Tere tulemast nimetule planeedile, mille omanikuks on [name].";
$l_planet_named		 = "Tere tulemast planeedile [planetname], mille omanikuks on [name].";
$l_planet_onsurface	 = "Sa oled maandunud planeedi pinnale.";
$l_planet_orbit 	 = "Sa tiirled planeedi orbiidil.";
$l_planet_leave_link     = "Lahku";
$l_planet_leave          = "[leave] planeedi pinnalt.";
$l_planet_name_link = "Nimeta";
$l_planet_name2 = "[name] planeet &uuml;mber.";
$l_planet_land_link      = "Maandu";
$l_planet_land           = "[land] planeedile.";
$l_planet_logout	 = "Sa v&otilde;id ka <a href=logout.php>v&auml;lja logida</a> ja loota, et see planeet Sind kaitseb.";
$l_planet_selling	 = "Planeet m&uuml;&uuml;b kaupu. ";
$l_planet_not_selling    = "See planeet ei m&uuml;&uuml; kaupu. ";
$l_planet_transfer_link	 = "Transpordi";
$l_planet_transfer	 = "[transfer] kaupu/koloniste planeedile/planeedilt.";
$l_planet_hasbase	 = "Sellel planeedil on baas.";

$l_planet_perc		 = "Tootlusprotsendid";
$l_planet_interest	 = "* Raha tootlus v&auml;ljaspool intressi on 100% - teised protsendid";
$l_planet_update	 = "Uuenda";
$l_planet_tsell_link	 = "L&uuml;lita &uuml;mber";
$l_planet_tsell		 = "[selling] planeedi kaupade m&uuml;&uuml;mist.";
$l_planet_bbase_link	 = "ehitada baasi";
$l_planet_bbase		 = "Piisava hulga raha ja kaupade olemasolu korral v&otilde;id Sa [build], mis aitab Su planeeti kaitsta.";
$l_planet_bbuild	 = "Baas on ehitatud.";
$l_planet_mcorp_linkC	 = "liidu planeedi";
$l_planet_mcorp_linkP	 = "isikliku planeedi";
$l_planet_mcorp		 = "Sa v&otilde;id teha sellest planeedist [planet].";
$l_planet_buy_link	 = "Osta";
$l_planet_buy		 = "[buy] planeedilt kaupa";
$l_planet_att_link	 = "R&uuml;nda";
$l_planet_att		 = "[attack] planeeti";
$l_planet_att_sure	 = " Oled Sa kindel...";
$l_planet_scn_link	 = "Skaneeri";
$l_planet_scn		 = "[scan] planeeti";
$l_planet_nowsell        = "N&uuml;&uuml;d m&uuml;&uuml;b planeet kaupa.";
$l_planet_nownosell      = "Planeet ei m&uuml;&uuml; enam kaupa.";
$l_planet_iname		 = "Sisesta planeedi uus nimi";
$l_planet_cname		 = "Planeedi uus nimi on ";
$l_planet_landed	 = "Sa oled maandunud planeedi pinnale.";
$l_planet_left		 = "Sa ei viibi enam planeedi pinnal.";
$l_planet_cinfo		 = "Sul on ruumi [cargo] &uuml;hikule laadungile ja [energy] &uuml;hikule energiale.";
$l_planet_toplanet	 = "Planeedile?";
$l_planet_baseinfo	 = "Et ehitada baasi, peab planeedil olema v&auml;hemalt " . NUMBER($base_credits) . " raha, " . NUMBER($base_ore) . " &uuml;hikut maaki, " . NUMBER($base_organics) . " &uuml;hikut oragaanikat ja " . NUMBER($base_goods) . " &uuml;hikut tarbekaupa.";
$l_planet_p_under        = "Sa ei saa muuta tootlusprotsente negatiivseks!";
$l_planet_p_over	 = "Sa ei saa summaarset tootlust muuta k&otilde;rgemaks kui 100%.";
$l_planet_p_changed	 = "Tootlusprotsendid muudetud.";
$l_plant_scn_turn	 = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et planeeti skaneerida.";
$l_planet_noscan	 = "Sensorid ei lukustunud sihikule!";
$l_planet_logscanA	 = "[name] &uuml;ritas skaneerida &uuml;hte Su planeeti sektoris [sector], kuid ei saanud hakkama.";
$l_planet_logscanB	 = "&Uuml;hte Su planeeti sektoris [sector] skaneeris m&auml;ngija [name].";
$l_planet_scn_report	 = "Planeedi [name] (omanik: [owner]) skaneeringu tulemused:";
$l_base	  		 = "Baas";
$l_planet_ison		 = "viibib planeedil.";
$l_planet_captured	 = "Planeet h&otilde;ivatud.";
$l_planet_notdef	 = "Planeet ei ole vallutatud!";
$l_planet_caplog	 = "[name] vallutas Su planeedi '[planetname]' sektoris [sector].";
$l_planet_noone = "teadmata";
$l_planet_readlog_link = "Vaata";
$l_planet_readlog = "[View] logi";

$l_planet2_title	 = "Transport planeedile/planeedilt";
$l_planet2_noturn	 = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et planeedile/planeedilt kaupa transportida.";
$l_planet2_noten 	 = "Sul ei ole piisavalt ";
$l_planet2_fortr	 = ", et kaupa vedada.";
$l_planet2_settr	 = "Kaubakogust muudeti, uus kogus: ";
$l_planet2_losup	 = "Planeedil on ainult ";
$l_planet2_notowner	 = "See ei ole Sinu planeet.";
$l_planet2_compl	 = "Transport l&otilde;petatud.";
$l_planet2_power	 = "ruumi";
$l_planet2_comp 	 = "pardaarvuti v&otilde;imsust";
$l_planet2_laun 	 = "torpeedoheitjate v&otilde;imsust";
$l_planet2_nocorptransfer = "Liidu planeedilt/planeedile ei saa raha &uuml;le kanda.";
$l_planet2_baseexceeded = "Ilma baasita planeedile ei mahu nii palju raha.";

$l_planet3_title	 = "Planeedil kauplemine";

// planet-report.php

$l_pr_title		 = "Planeedi raport";
$l_pr_teamlink		 = "N&auml;ita liidu planeete";
$l_pr_noplanet		 = "Sul ei ole planeete";
$l_pr_clicktosort	 = "Kliki tulba pealkirjal, et sortida.";
$l_pr_totals		 = "Kokku";

// rsmove.php
$l_rs_title 		= "Liikumine avakosmoses";
$l_rs_whichsector       = "Kuhu sektorisse Sa soovid lennata?";
$l_rs_insector		= "Sa oled praegu sektoris [sector] ja Sa v&otilde;id lennata sektoritesse 0 kuni [sector_max].";
$l_rs_submit		= "Arvuta";
$l_rs_movetime		= "Praeguste mootoritega v&otilde;tab see reis aega [triptime] k&auml;iku.";
$l_rs_energy		= "Teel olles genereeritakse [energy] &uuml;hikut energiat";
$l_rs_noturns		= "Sule ei ole piisavalt k&auml;ike, et seda reisi ette v&otilde;tta.";
$l_rs_engage_link	= "K&auml;ivita";
$l_rs_engage		= "Sul on [turns] k&auml;iku. [engage] mootorid?";

$l_rs_invalid		= "Viga sihtpunkti m&auml;&auml;ratlemisel";
$l_rs_ready 		= "Oled j&otilde;udnud sektorisse [sector]. Sa kulutasid selleks [triptime] k&auml;iku ja genereerisid [energy] &uuml;hikut energiat.";

// navcomp.php

$l_nav_title		 = "Pardakompuuter";
$l_nav_nocomp		 = "Pardakompuutrit ei saa kasutada";
$l_nav_query		 = "Sisesta sektor, kuhu soovid j&otilde;uda: ";
$l_nav_pathfnd		 = "Tee leitud";
$l_nav_answ1		 = "Sinna sektorisse j&otilde;udmine v&otilde;tab";
$l_nav_answ2		 = "k&auml;iku.";
$l_nav_proper		 = "Su pardaarvuti on liiga algeline, et nii pikka varp-teed leida.";


// attack.php

$l_att_title		 = "Laeva r&uuml;ndamine";
$l_att_notarg		 = "Sihtm&auml;rk ei ole selles sektoris.";
$l_att_noturn		 = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et r&uuml;nnata.";
$l_att_noatt		 = "Selles sektoris ei tohi kedagi r&uuml;nnata.";
$l_att_flee		 = "Sihtm&auml;rk lendas eest &auml;ra!";
$l_att_ewd		 = "Sihtm&auml;rk kasutas h&auml;daabi varpi!";
$l_att_att		 = "R&uuml;ndad ";
$l_att_beams		 = "Laserid tulistasid:";
$l_att_torps		 = "Torpeedod tulistati v&auml;lja:";
$l_att_fighters		 = "H&auml;vitajad r&uuml;ndasid:";
$l_att_lost		 = "kaotas";
$l_att_ylost		 = "Sa kaotasid";
$l_att_sdown		 = " energiakilp on purustatud!";
$l_att_ydown		 = "Su energiakilp on purustatud!";
$l_att_shits		 = " energiakilp sai vigastada";
$l_att_yhits		 = "Su energiakilp sai vigastada";
$l_att_dmg		 = "punkti ulatuses";
$l_att_sarm		 = " soomus on t&auml;ielikult purustatud!";
$l_att_yarm		 = "Su laeva soomus on t&auml;ielikult purustatud!";
$l_att_ashit		 = " soomus sai vigastada";
$l_att_ayhit		 = "Su soomus sai vigastada";
$l_att_lostf		 = "kaotas k&otilde;ik h&auml;vitajad.";
$l_att_ylostf		 = "Sa kaotasid k&otilde;ik h&auml;vitajad.";
$l_att_sdest		 = " laev on h&auml;vitatud!";
$l_att_espod		 = "H&auml;vivast laevast eraldus p&auml;&auml;stekapsel.";
$l_att_ysalv		 = "Sa said vrakilt k&auml;tte [salv_ore] &uuml;hikut maaki, [salv_organics] &uuml;hikut orgaanikat, [salv_goods] &uuml;hikut tarbekaupu ja [ship_salvage_rate]% laevast v&auml;&auml;rtusega [ship_salvage] raha.<BR>Su reiting muutus [rating_change] punkti v&otilde;rra. ";
$l_att_andused		 = "ja kasutasid";
$l_att_stilship		 = "Sa ei suutnud purustada [name] laeva.";
$l_att_atyou		 = "r&uuml;ndas Sind";
$l_att_and		 = "ja";
$l_att_yshiplost	 = "Su laev on purustatud!";
$l_att_salv		 = "[name] sai [salv_ore] &uuml;hikut maaki, [salv_organics] &uuml;hikut orgaanikat, [salv_goods] &uuml;hikut tarbekaupu ja [ship_salvage_rate]% laevast v&auml;&auml;rtusega [ship_salvage] raha.";

// warpedit 1-3.php

$l_warp_title		 = "Varbimuunduri kasutamine";
$l_warp_turn		 = "Et kasutada varbimuundurit, peab Sul olema v&auml;hemalt &uuml;ks k&auml;ik.";
$l_warp_none		 = "Sul ei ole &uuml;htegi varbimuundurit.";
$l_warp_forbid		 = "Siin sektoris ei tohi varbimuundureid kasutada.";
$l_warp_nolink		 = "Sellest sektorist ei v&auml;lju &uuml;htegi varp-koridori.";
$l_warp_linkto		 = "Siit sektorist v&auml;ljuvad varp-koridorid j&auml;rgmistesse sektoritesse:";
$l_warp_query		 = "Millisesse sektorisse Sa soovid luua varp-koridori?";
$l_warp_oneway		 = "&Uuml;hesuunalist";
$l_warp_dest		 = "Sa v&otilde;id ka h&auml;vitada varp-koridore.";
$l_warp_destquery	 = "Millise sektori varp-koridori Sa h&auml;vitada soovid?";
$l_warp_bothway		 = "M&otilde;lemad suunad";
$l_warp_nosector	 = "Sektorit ei ole.";
$l_warp_twoerror	 = "Kahesuunalise varp-koridori loomine sektoriga [target_sector] ei ole lubatud.";
$l_warp_sectex		 = "Ei saa tekitada veel &uuml;hte varp-koridori sellest sektorist - k&otilde;ik lubatud $link_max koridori sektori kohta on juba olemas.";
$l_warp_linked		 = "Sihtpunkti (sektor [target_sector]) on siit juba varp-koridor olemas.";
$l_warp_unlinked	 = "Sihtpunktist (sektor [target_sector]) ei ole varp-koridori siia sektorisse.";
$l_warp_coneway	         = "Loodi &uuml;hesuunaline varp-koridor sektorisse";
$l_warp_ctwoway		 = "Loodi kahesuunaline varp-koridor sektoriga";
$l_warp_forbidtwo	 = "Varp-koridori m&otilde;lema suuna h&auml;vitamine sektoriga [target_sector] ei ole lubatud.";
$l_warp_removed		 = "H&auml;vitati varp-koridor sektorisse";
$l_warp_removedtwo	 = "H&auml;vitati m&otilde;lemasuunaline varp-koridor sektoriga";

// genesis.php

$l_gns_title		 = "Mateeriatorpeedo kasutamine";
$l_gns_turn		 = "Et kasutada mateeriatorpeedot, peab Sul v&auml;hemalt &uuml;ks k&auml;ik olema.";
$l_gns_onplanet		 = "Planeedi pinnal olles ei saa nii v&otilde;imast seadet kasutada.";
$l_gns_full		 = "Selle sektori t&auml;hes&uuml;steem on juba t&auml;is.";
$l_gns_planetex		 = "Selles sektoris on juba planeet.";
$l_gns_nogenesis	 = "Sul ei ole &uuml;htegi mateeriatorpeedot.";
$l_gns_forbid		 = "Selles sektoris ei ole lubatud mateeriatorpeedot kasutada.";
$l_gns_bforbid		 = "Selle sektori baasid ei lase Sul mateeriatorpeedot kasutada.";
$l_gns_pcreate		 = "Planeet loodud!";

// ship.php

$l_ship_title		 = "Laeva men&uuml;&uuml;";
$l_ship_the		 = "Laev";
$l_ship_nolonger	 = "ei ole enam sektoris";
$l_ship_youc		 = "Sa n&auml;ed laeva";
$l_ship_owned		 = " mille omanikuks on";
$l_ship_perform		 = "Sa saad teha j&auml;rgnevat:";

// selfdestruct.php

$l_die_title		 = "Eneseh&auml;vitus";
$l_die_rusure		 = "Kas Sa oled kindel, et tahad oma laeva h&auml;vitada? See eemaldab Su sellest m&auml;ngust.";
$l_die_goodbye		 = "H&uuml;vasti, julm galaktika!";
$l_die_check		 = "Kas Sa oled ikka p&auml;ris kindel, et Sa soovid sellest m&auml;ngust lahkuda?";
$l_die_nonono		 = "EI! EI! EI!";
$l_die_what		 = "Mida ma k&uuml;ll m&otilde;tlesin?";
$l_die_count		 = "5.. 4.. 3.. 2.. 1.. H&auml;ving!";
$l_die_vapor		 = "Su laev aurustus koos meeskonna ja laadungiga.";
$l_die_please		 = "Palun <A HREF=logout.php>logi v&auml;lja</A>";
$l_die_exploit		 = "&Auml;ra m&auml;ngi asjadega, millest Sa aru ei saa.";

// move.php

$l_move_title 		 = "Varpimine";
$l_move_turn		 = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et varpida.";
$l_move_failed		 = "Varpimine eba&otilde;nnestus!";

// scan.php

$l_scan_title		 = "Laeva skaneering";
$l_scan_turn		 = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et teist laeva skaneerida.";
$l_scan_ron		 = "Skaneerisid laeva";
$l_scan_capt		 = "mille omanik on";
$l_scan_arma		 = "Varustus:";
$l_scan_carry		 = "Laadung:";

// lrscan.php

$l_lrs_title		 = "Vaatlus";
$l_lrs_nofull		 = "Su skannerid ei v&otilde;imalda t&auml;isvaatlust.";
$l_lrs_noturns		 = "Sul peab olema v&auml;hemalt $fullscan_cost k&auml;ik(u), et teostada t&auml;isvaatlust.";
$l_lrs_used		 = "Kasutasid";
$l_lrs_turns		 = "k&auml;igu";
$l_lrs_left		 = "k&auml;iku j&auml;i j&auml;rgi";
$l_lrs_reach		 = "Sektorist [sector] saab varpida j&auml;rgmistesse sektoritesse:";
$l_lrs_links		 = "Varp-koridorid";
$l_lrs_ships		 = "Laevad";
$l_lrs_click		 = "Kliki &uuml;hele linkidest, et varpida vastavasse sektorisse.";
$l_lrs_cantscan		 = "Seda sektorit ei saa siit vaadelda!";
$l_lrs_zero		 = "Sektor 0 on liiga t&auml;is, et eristada laevu!";
$l_lrs_moveto		 = "et liikuda sektorisse";
$l_log_titlet = "Logiraamat";

// log.php

$l_log_months = array('jaanuar','veebruar','m&auml;rts','aprill','mai','juuni','juuli','august','september','oktoober','november','detsember');
$l_log_months_short = array('Jaan','Veebr','M&auml;rts','Apr','Mai','Juuni','Juuli','Aug','Sept','Okt','Nov','Dets');
$l_log_pod = "&Otilde;nneks oli Sul p&auml;&auml;stekapsel!";
$l_log_nopod = "<font color=yellow><b>Sul ei olnud p&auml;&auml;stekapslit. Sa hukkusid.</b></font>";
$l_log_log = "M&auml;ngija [player] logi";
$l_log_start = "Sissekanded:";
$l_log_end = "Logi l&otilde;pp:";
$l_log_click = "Vajuta <A HREF=main.php><font color=#00ff00>siia</font></A> et minna peamen&uuml;&uuml;sse.";
$l_log_note = "PS: Kui see lehek&uuml;lg n&auml;ib ebakorrektne v&otilde;i Sulle lihtsalt ei meeldi d&uuml;naamilise html-i efektid v&otilde;i segavad nad Sind, siis v&otilde;id Sa need <a href=options.php><font color=#00FF00>siin</font></a> v&auml;lja l&uuml;litada.";

$l_log_text[LOG_LOGIN] = "Logisid sisse aadressilt [ip].";
$l_log_title[LOG_LOGIN] = "Sisse logimine";
$l_log_text[LOG_LOGOUT] = "Logisid v&auml;lja aadressilt [ip].";
$l_log_title[LOG_LOGOUT] = "V&auml;lja logimine";
$l_log_text[LOG_ATTACK_OUTMAN] = "[player] v&otilde;ttis Su laeva sihikule, aga Su piloodioskused ja head mootorid v&otilde;imaldasid Sul vaenlase eest &auml;ra lennata.";
$l_log_title[LOG_ATTACK_OUTMAN] = "P&otilde;genemine!";
$l_log_text[LOG_ATTACK_OUTSCAN] = "Su sensorid avastasid, et m&auml;ngija [player] relvad &uuml;rituvad Su laevale lukustuda, aga Su radarisegajad suutsid vaenlase primitiivseid sensoreid lollitada.";
$l_log_title[LOG_ATTACK_OUTSCAN] = "Segamine &otilde;nnestus!";
$l_log_text[LOG_ATTACK_EWD] = "Sind tabas m&auml;ngija [player] reeturlik r&uuml;nnak. Sa j&otilde;udsid veel n&auml;ha vaenlase l&otilde;hkepeade l&auml;henemist, enne kui Sa h&auml;daabi varbi nupule vajutasid. Maailm &auml;hmastus korraks, ja Sa arvasid, et Sa oledki juba surnud. Kui Sa l&otilde;puks ikkagi silmad avasid, n&auml;gid Sa, et Su laev on turvaliselt mujale kantud. Aga kuhu, seda Sa ei tea...";
$l_log_title[LOG_ATTACK_EWD] = "H&auml;daabi varp!";
$l_log_text[LOG_ATTACK_EWDFAIL] = "Su sensorid avastasid, et m&auml;ngija [player] laev on Su sihikule v&otilde;tnud. \"Parem laev varpida kui p&auml;&auml;stekapsel Sol-i parkida,\" m&otilde;tlesid Sa h&auml;daabi varbi nuppu vajutades. Mootoriruumist kostis imelik heli ja Sa tundsid p&otilde;leva isolatsiooni l&otilde;hna. \"K****i varp v&otilde;i asi!\", karjatasid Sa, pekstes vaest pardaarvutit. Arvuti piiksus suurest pahameelest, kuid Sa olid sunnitud valmistuma l&auml;henevaks v&otilde;itluseks ja ei kuulanud seda enam...";
$l_log_title[LOG_ATTACK_EWDFAIL] = "H&auml;daabi varp <font color=red>ei t&ouml;&ouml;tanud!</font>";
$l_log_text[LOG_ATTACK_LOSE] = "[player] r&uuml;ndas Su laeva. Proovisid, mis Sa proovisid, Sa ei suutnud t&otilde;rjuda m&auml;ngija [player] superrelvi. Su laev purustati. ";
$l_log_title[LOG_ATTACK_LOSE] = "<font color=red>Lahing kaotatud!</font>";
$l_log_text[LOG_ATTACKED_WIN] = "[player] r&uuml;ndas Su laeva. P&auml;rast l&uuml;hikest v&otilde;itlust lahingutegevus peatus. Sa kaotasid [armor] soomusepunkti ja [fighters] h&auml;vitajat.";
$l_log_title[LOG_ATTACKED_WIN] = "<font color=yellow>T&uuml;hi v&otilde;itlus</font>";
$l_log_text[LOG_TOLL_PAID] = "Sa olid sunnitud maksma [toll] raha, et sieneda sektorisse [sector]. Sa lubasid endale, et Sa leiad viisi, kuidas oma raha tagasi saada.";
$l_log_title[LOG_TOLL_PAID] = "V&auml;ljapressimine!";
$l_log_text[LOG_HIT_MINES] = "Sa p&otilde;rkasid vastu [mines] miini, kui Sa liikusid sektoris [sector].";
$l_log_title[LOG_HIT_MINES] = "<font color=yellow>Miinihoiatus!</font>";
$l_log_text[LOG_SHIP_DESTROYED_MINES] = "Su laev h&auml;vis miiniv&auml;ljal sektoris [sector]. ";
$l_log_title[LOG_SHIP_DESTROYED_MINES] = "<font color=red>Miiniv&auml;li!</font>";
$l_log_text[LOG_PLANET_DEFEATED_D] = "[name] alistas Su planeedi [planet_name] sektoris [sector]. &Otilde;nneks olid sealsed elanikud Sulle nii lojaalsed, et otsustasid ennast pigem koos planeediga h&auml;vitada kui et langeda sellise j&otilde;hkardi meelevalda. Sa organiseerisid suure matuseteenistuse, et m&auml;lestada neid vapraid inimesi, kes end koos planeediga ohverdasid.";
$l_log_title[LOG_PLANET_DEFEATED_D] = "<font color=yellow>Planeet h&auml;vitatud!</font>";
$l_log_text[LOG_PLANET_DEFEATED] = "Nurjatu [name] alistas Su planeedi [planet_name] sektoris [sector]. Planeedi elanikud lausa tervitasid oma uut valitsejat! Sa kuulsid BNN teadet: \"Saime ometi l&otilde;puks sellest vanast tolast lahti! Meile ei meeldi valitsejad, kes meid kaitsta ei suuda!\". Sa vandusid, et nad veel maksavad oma jultumuse eest...";
$l_log_title[LOG_PLANET_DEFEATED] = "<font color=red>Planeet alistatud!</font>";
$l_log_text[LOG_PLANET_NOT_DEFEATED] = "[name] r&uuml;ndas Su planeeti [planet_name] sektoris [sector]. Planeedi elanikud osutasid sissetungijale ennast&uuml;letavat vastupanu ja suutsid m&auml;ngija [name] laeva h&auml;vitada. Rusudest &otilde;nnestus neil isegi midagi k&auml;tte saada : [goods] tarbekaupa, [ore] maaki, [organics] orgaanikat ja [salvage]% laevast v&auml;&auml;rtusega [credits] raha.";
$l_log_title[LOG_PLANET_NOT_DEFEATED] = "V&otilde;it!";
$l_log_title[LOG_RAW] = "Teade:";
$l_log_text[LOG_TOLL_RECV] = "Sinu h&auml;vitajad sektoris [sector] kogusid [toll] raha tollimaksu.";
$l_log_title[LOG_TOLL_RECV] = "Sissetulek";
$l_log_text[LOG_DEFS_DESTROYED] = "[quantity] [type] purustati sektoris [sector].";
$l_log_title[LOG_DEFS_DESTROYED] = "Sektori kaitsed purustatud";
$l_log_text[LOG_PLANET_EJECT] = "Sind sunniti sektoris [sector] planeedilt lahkuma, sest [name] lahkus liidust.";
$l_log_title[LOG_PLANET_EJECT] = "V&auml;lja visatud!";
$l_log_text[LOG_BADLOGIN] = "Viga sisse logimisel aadressilt [ip].";
$l_log_title[LOG_BADLOGIN] = "Viga sisse logimisel";
$l_log_text[LOG_PLANET_SCAN] = "[name] skaneeris Su planeeti [planet_name] sektoris [sector].";
$l_log_title[LOG_PLANET_SCAN] = "Planeet skaneeritud";
$l_log_text[LOG_PLANET_SCAN_FAIL] = "[name] &uuml;ritas skaneerida Su planeeti [planet_name] sektoris [sector], aga ei saanud midagi teada.";
$l_log_title[LOG_PLANET_SCAN_FAIL] = "Planeeti &uuml;ritati skaneerida";
$l_log_text[LOG_SHIP_SCAN] = "[player] skaneeris Su laeva.";
$l_log_title[LOG_SHIP_SCAN] = "Laev skaneeritud";
$l_log_text[LOG_SHIP_SCAN_FAIL] = "[player] &uuml;ritas skaneerida Su laeva, aga ei saanud midagi teada.";
$l_log_title[LOG_SHIP_SCAN_FAIL] = "Laeva &uuml;ritati skaneerida";
$l_log_text[LOG_FURANGEE_ATTACK] = "R&uuml;ndan m&auml;ngijat [player]...";
$l_log_title[LOG_FURANGEE_ATTACK] = "R&uuml;nnak";
$l_log_text[LOG_STARVATION] = "&Uuml;ks Su planeet sektoris [sector] ei suuda oma elanikkonda toita! Vajatakse rohkem orgaanikat. [starvation] kolonisti suri n&auml;lga.";
$l_log_title[LOG_STARVATION] = "<font color=yellow>N&auml;ljah&auml;da!</font>";
$l_log_title[LOG_TOW] = "V&auml;lja t&otilde;stetud!";
$l_log_text[LOG_DEFS_DESTROYED_F] = "Sa purustasid [fighters] h&auml;vitajat sektoris [sector].";
$l_log_title[LOG_DEFS_DESTROYED_F] = "H&auml;vitajad purustatud";
$l_log_text[LOG_DEFS_KABOOM] = "H&auml;vitajad purustasid Su laeva sektoris [sector]. ";
$l_log_title[LOG_DEFS_KABOOM] = "<font color=red>Laev purustatud!</font>";
$l_log_text[LOG_HARAKIRI] = "Sa t&uuml;dinesid sellest m&auml;ngust ja leidsid, et galaktika n&auml;eb ilma Sinuta parem v&auml;lja. Seega - Sa h&auml;vitasid oma laeva. Kinnitatud aadressilt [ip].";
$l_log_title[LOG_HARAKIRI] = "<font color=red>Eneseh&auml;vitus!</font>";
$l_log_text[LOG_TEAM_REJECT] = "[player] keeldus Su liiduga [teamname] &uuml;hinemast.";
$l_log_title[LOG_TEAM_REJECT] = "Kutse tagasi l&uuml;katud";
$l_log_text[LOG_TEAM_RENAME] = "Sa nimetasid oma liidu &uuml;mber. Uueks nimeks sai [team].";
$l_log_title[LOG_TEAM_RENAME] = "Liit &uuml;mber nimetatud";
$l_log_text[LOG_TEAM_M_RENAME] = "Sinu liidu koordinaator nimetas liidu &uuml;mber. Uueks nimeks sai [team].";
$l_log_title[LOG_TEAM_M_RENAME] = "Liit &uuml;mber nimetatud";
$l_log_text[LOG_TEAM_KICK] = "Sind visati liidust [team] v&auml;lja.";
$l_log_title[LOG_TEAM_KICK] = "Liidust v&auml;lja visatud!";
$l_log_text[LOG_TEAM_CREATE] = "Sa oled loonud uue liidu [team].";
$l_log_title[LOG_TEAM_CREATE] = "Uus liit loodud";
$l_log_text[LOG_TEAM_LEAVE] = "Sa oled lahkunud liidust [team].";
$l_log_title[LOG_TEAM_LEAVE] = "Liidust lahkunud";
$l_log_text[LOG_TEAM_NEWLEAD] = "Sa oled lahkunud liidust [team]. Sa andsid koordinaatori vastutusrikka rolli &uuml;le m&auml;ngijale [name].";
$l_log_title[LOG_TEAM_NEWLEAD] = "Liidust lahkunud";
$l_log_text[LOG_TEAM_LEAD] = "Su liidu [team] koordinaator otsustas liidust lahkuda. Sind on m&auml;&auml;ratud tema vastutusrikkale ametikohale.";
$l_log_title[LOG_TEAM_LEAD] = "Ametik&otilde;rgendus!";
$l_log_text[LOG_TEAM_JOIN] = "Sa &uuml;hinesid liiduga [team].";
$l_log_title[LOG_TEAM_JOIN] = "&Uuml;hinenud liiduga";
$l_log_text[LOG_TEAM_NEWMEMBER] = "[name] n&otilde;ustus &uuml;hinema liiduga [team]. J&auml;lle &uuml;ks kivi galaktika &uuml;lemv&otilde;imu m&uuml;&uuml;ris!";
$l_log_title[LOG_TEAM_NEWMEMBER] = "Uus liige";
$l_log_text[LOG_TEAM_INVITE] = "Sind on kutsutud &uuml;hinema liiduga [team].";
$l_log_title[LOG_TEAM_INVITE] = "Kutse";
$l_log_text[LOG_TEAM_NOT_LEAVE] = "[player] lahkus Su liidust.";
$l_log_title[LOG_TEAM_NOT_LEAVE] = "Liit kaotas &uuml;he liikme";
$l_log_text[LOG_ADMIN_HARAKIRI] = "[player] tegi aadressilt [ip] eneseh&auml;vituse.";
$l_log_title[LOG_ADMIN_HARAKIRI] = "Eneseh&auml;vitus";
$l_log_text[LOG_ADMIN_ILLEGVALUE] = "M&auml;ngijal [player] oli [quantity] [type], maksimaalselt suutis ta kanda [holds].";
$l_log_title[LOG_ADMIN_ILLEGVALUE] = "Lubamatu kogus laeval";
$l_log_text[LOG_ADMIN_PLANETDEL] = "[attacker] &uuml;ritas vallutada m&auml;ngija [defender] planeeti sektoris [sector]. Elanikud h&auml;vitasid planeedi.";
$l_log_title[LOG_ADMIN_PLANETDEL] = "Planeet h&auml;vitatud";
$l_log_text[LOG_DEFENCE_DEGRADE] = "Sektori kaitse h&auml;vitajad sektoris [sector] v&auml;henesid [degrade] protsenti energianappuse t&otilde;ttu.";
$l_log_test[LOG_DEFENCE_DEGRADE] = "<font color=yellow>Sektori kaitseid v&auml;hem!</font>";
$l_log_text[LOG_PLANET_CAPTURED] = "Sa alistasid planeedi, mille omanik oli [owner]. Sellel oli [cols] kolonisti ja [credits] raha.";
$l_log_title[LOG_PLANET_CAPTURED] = "Planeet alistatud!";
$l_log_text[LOG_CHEAT_TEAM] = "M&auml;ngija [player] IP-aadressilt [ip] &uuml;ritas kedagi v&otilde;&otilde;rast liidust v&auml;lja visata. Tema laev h&auml;vitati!";

// modify-defences.php

$l_md_title		 = "Sektori kaitsed";
$l_md_invalid		 = "Ebakorrektne sektori kaitse";
$l_md_nolonger		 = "Sektori kaitset ei ole enam siin.";
$l_md_you		 = "oled Sina";
$l_md_bmines		 = "Sinu laserid purustasid";
$l_md_msgdownerb	 = "[name] h&auml;vitas [mines] miini sektoris [sector].";
$l_md_retr		 = "Sa v&otilde;tsid tagasi";
$l_md_mode		 = "Valitud h&auml;vitajad on viidud olekusse [mode].";
$l_md_consist		 = "See sektori kaitse koosneb [qty]-st [type], mille omanikuks [owner].";
$l_md_youcan		 = "Sa v&otilde;id";
$l_md_retrieve		 = "tagasi v&otilde;tta";
$l_md_change		 = "h&auml;vitajate olekut muuta";
$l_md_cmode		 = "H&auml;vitajate olek:";
$l_md_attack		 = "R&uuml;nnak";
$l_md_toll		 = "Toll";
$l_md_attdef		 = "Sa v&otilde;id sektori kaitseid r&uuml;nnata. K&otilde;ik sektori kaitse h&auml;vitajad r&uuml;ndavad Sind.";
$l_md_noturn	  	 = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik.";
$l_md_nothere            = "Sa pead olema sektori kaitsetega samas sektoris.";
$l_md_notyours           = "K&auml;sk t&auml;itmata. Need sektori kaitsed ei kuulu Sulle.";
$l_md_yours              = "Sa ei saa r&uuml;nnata Sinu isiklikke sektori kaitseid.";

// news.php

$l_news_title		 = "BlackNova Universumi Uudised";
$l_news_info		 = "BNN on koos galaktika valitsejatega,<br>
                            et vahendada uudiseid ja infot.<br>
                            Me t&ouml;&ouml;tame 24 tundi p&auml;evas ja 7 p&auml;eva n&auml;dalas<br>
                            BNN'i galaktilises peakorteris <br>
                            Alpha Centauril ja b&uuml;roodes &uuml;le terve galaktika!";
$l_news_for		 = "Uudised:";
$l_news_prev		 = "eelmine p&auml;ev";
$l_news_next		 = "j&auml;rgmine p&auml;ev";
$l_news_none		 = "T&auml;na pole &uuml;htegi uudist.";
$l_news_flash		 = "Pealkirjaveerg";

// dump.php

$l_dump_title		 = "Kolonistide Maale saatmine";
$l_dump_turn		 = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et koloniste Maale saata.";
$l_dump_nocol		 = "Sule ei ole &uuml;htegi kolonisti pardal.";
$l_dump_dumped		 = "Kolonistid on laevalt lahkunud.";
$l_dump_nono		 = "Sa pead olema keskjaamas, et seda teha.";

// readmail.php

$l_readm_title		 = "Teadete lugemine";

$l_readm_delete		 = "Teade kustutatud";
$l_readm_nomessage	 = "Sind ei oota &uuml;kski teade...<BR>";
$l_readm_center		 = "Teadete keskus";
$l_readm_sender		 = "Saatja";
$l_readm_captn		 = "Kapten laeval";
$l_readm_del		 = "Kustuta";
$l_readm_repl		 = "Vasta";

// mailto2.php

$l_sendm_title		 = "Teate saatmine";
$l_sendm_to		 = "Saaja";
$l_sendm_from		 = "Saatja";
$l_sendm_ally		 = "Liit:";
$l_sendm_subj		 = "Pealkiri";
$l_sendm_mess		 = "Teade";
$l_sendm_send		 = "Saada";
$l_sendm_sent		 = "Teade saadetud";

// zoneinfo.php

$l_zi_title		 = "Tsooni info";
$l_zi_nexist		 = "Sellist kosmilist sektsiooni ei eksisteeri!";
$l_zi_feds		 = "F&ouml;deratsioon";
$l_zi_traders		 = "Vabakaubanduskoalitsioon";
$l_zi_nobody		 = "Keegi";
$l_zi_war		 = "Vaenuv&auml;ed";
$l_zi_allow		 = "Lubatud";
$l_zi_notallow		 = "Keelatud";
$l_zi_limit		 = "Lubatud omanikule ja liidule";
$l_zi_ul		 = "Piiramatu";
$l_zi_control		 = "See sektor on Sinu kontrolli all";
$l_zi_tochange		 = "et muuta selle reegleid.";
$l_zi_owner		 = "Tsooni omanik";
$l_zi_maxhull		 = "Suurim lubatud keskmine tehniline tase";

// zoneedit.php

$l_ze_title		 = "Tsooni muutmine";
$l_ze_notowner		 = "Sa ei ole selle tsooni omanik, seega ei saa Sa selle reegleid muuta.";
$l_ze_name		 = "Tsooni nimi";
$l_ze_allow		 = "Luba";
$l_ze_attacks		 = "Luba laevade r&uuml;ndamine";
$l_ze_genesis		 = "Luba uute planeetide tekitamine";
$l_ze_return		 = "et minna tsooni info lehele";
$l_ze_saved		 = "Muudatused salvestatud.";

// teams.php

$l_team_title		 = "Liidud";
$l_team_menu		 = "et minna tagasi liitude lehele";
$l_team_galax		 = "Praegu on galaktikas j&auml;rgmised liidud:";
$l_team_members		 = "Liikmed";
$l_team_coord		 = "Koordinaator";
$l_team_member		 = "Liige";
$l_team_noinvite	 = "Keegi ei ole Sind &uuml;hegi liiduga &uuml;hinema kutsunud.";
$l_team_ifyouwant	 = "Kui Sa soovid m&otilde;ne liiduga &uuml;hineda, saada selle koordinaatorile teade, et ta Sind kutsuks.";
$l_team_tocreate	 = "et luua uus liit.";
$l_team_injoin		 = "Sind on kutsutud &uuml;hinema liiduga";
$l_team_tojoin		 = "et &uuml;hineda";
$l_team_or		 = "v&otilde;i";
$l_team_reject		 = "et mitte &uuml;hineda.";
$l_team_ed		 = "Muuda";
$l_team_inv		 = "Kutsu";
$l_team_leave		 = "Lahku";
$l_team_eject		 = "Viska v&auml;lja";
$l_team_pending		 = "M&auml;ngijad, kes on kutsutud &uuml;hinema liiduga ";
$l_team_noinvites	 = "&Uuml;kski m&auml;ngija ei ole kutsutud &uuml;hinema liiduga ";
$l_team_confirmleave	 = "Oled Sa kindel, et soovid lahkuda liidust";
$l_team_onlymember	 = "Sa olid viimane liige liidus [team_name], seega seda liitu ei ole enam.";
$l_team_youarecoord	 = "Sa oled koordinaator liidule";
$l_team_relinq		 = "Sa pead oma kohustused kellelegi &uuml;le andma.";
$l_team_newc		 = "Uus koordinaator:";
$l_team_youveleft	 = "Sa lahkusid liidust";
$l_team_relto		 = "j&auml;ttes koordinaatori&uuml;lesanded m&auml;ngijale";
$l_team_welcome		 = "Tere tulemast liitu";
$l_team_noinviteto	 = "Sind ei ole siia liitu kutsutud!";
$l_team_ejectsure	 = "Oled Sa kindel, et Sa soovid v&auml;lja visata m&auml;ngija";
$l_team_ejected 	 = "on liidust v&auml;lja visatud!";
$l_team_testing		 = "Testimine...";
$l_team_pw		 = "Parool";
$l_team_entername	 = "Sisesta liidu nimi";
$l_team_enterdesc	 = "Sisesta liidu kirjeldus";
$l_team_hcreated	 = "on loodud ja sina oled selle koordinaator";
$l_team_alliance	 = "Liit";
$l_team_selectp		 = "Vali m&auml;ngija, keda soovid &uuml;hinema kutsuda";
$l_team_isorry		 = "Kahjuks on m&auml;ngija [name] juba kuskile liitu kutsutud - iga m&auml;ngija saab korraga olla kutsutud vaid &uuml;hte liitu";
$l_team_plinvted	 = "M&auml;ngija kutsutud.<BR>Sa pead ootama, kuni m&auml;ngija Su kutsele vastab.";
$l_team_refuse		 = "Sa l&uuml;kkasid tagasi pakkumise &uuml;hineda liiduga";
$l_team_edname		 = "Muuda oma liidu nime";
$l_team_eddesc		 = "Muuda oma liidu kirjeldust";
$l_team_hasbeenr	 = "on &uuml;mber nimetatud.";
$l_team_error		 = "<b><font color=red>VIGA</font></b><br>Sa ei ole selle liidu koordinaator.";
$l_team_notmember	 = "Sa ei ole &uuml;hegi liidu liige";
$l_team_urejected	 = "<B>HOIATUS</B> - Sind on v&auml;lja visatud liidust";
$l_team_noalliances	 = "Galaktikas ei ole praegu &uuml;htegi liitu.";

// ranking.php

$l_ranks_title		 = "Top $max_rank m&auml;ngijad";
$l_ranks_none		 = "Pole midagi n&auml;idata.";
$l_ranks_pnum		 = "M&auml;ngijaid kokku";
$l_ranks_dships		 = "M&auml;ngijad, kelle laev on purustatud, ei ole siia tabelisse kaasatud.";
$l_ranks_rank		 = "Koht";
$l_ranks_lastlog	 = "Viimati";
$l_ranks_good		 = "Hea";
$l_ranks_evil		 = "Halb";

// beacon.php

$l_beacon_title		 = "Majaka seadmine";
$l_beacon_notpermitted	 = "Siia sektorisse ei tohi majakaid p&uuml;stitada.";
$l_beacon_reads		 = "Praegune majakas teatab";
$l_beacon_none		 = "Siin ei ole praegu majakat.";
$l_beacon_enter		 = "Sisesta majaka tekst";
$l_beacon_nowreads	 = "Majakas teatab n&uuml;&uuml;d";
$l_beacon_donthave	 = "Sul ei ole &uuml;htegi majakat.";

// emerwarp.php

$l_ewd_title		 = "H&auml;daabi varbi kasutamine";
$l_ewd_used		 = "H&auml;daabi varp aktiveeritud - sattusid sektorisse [sector].";
$l_ewd_none		 = "Sul ei ole h&auml;daabi varpe.";

// defence-report.php

$l_sdf_title		 = "Sektori kaitsed";
$l_sdf_none		 = "Sul ei ole &uuml;les seatud sektori kaitseid.";
$l_sdf_type		 = "T&uuml;&uuml;p";
$l_sdf_mode		 = "Olek";

// traderoute.php
// cause its rather big i put everything in own vars than to re-use
// the old ones so we could export to own file if performance problems
// should occur

$l_tdr_within      = " sektoris ";
$l_tdr_title    	 = "Kaubateed";
$l_tdr_newtdr   	 = "Vajuta <a href=\"traderoute.php?command=new\">siia</a> et luua uus kaubatee.";
$l_tdr_modtdrset         = "Vajuta <a href=\"traderoute.php?command=settings\">siia</a> et muuta kaubateede &uuml;ldisi seadeid.";
$l_tdr_confdel  	 = "<B>Vajuta <a href=\"traderoute.php?command=delete&confirm=yes&traderoute_id=[tdr_id]\">siia</a> et kinnitada j&auml;rgneva kaubatee kustutamist:</B>";
$l_tdr_noactive 	 = "Sul ei ole &uuml;htegi kaubateed.";
$l_tdr_curtdr   	 = "Praegused kaubateed";
$l_tdr_deltdr   	 = "Kustuta kaubatee";
$l_tdr_src      	 = "Algus";
$l_tdr_srctype  	 = "Alguse t&uuml;&uuml;p";
$l_tdr_dest     	 = "L&otilde;pp";
$l_tdr_desttype 	 = "L&otilde;pu t&uuml;&uuml;p";
$l_tdr_move     	 = "Liikumine";
$l_tdr_circuit  	 = "&Uuml;hendus";
$l_tdr_change   	 = "Tegevus";
$l_tdr_portin   	 = "Sadam sektoris";
$l_tdr_planet   	 = "Planeet";
$l_tdr_nonexistance      = "Mitte-eksisteeriv planeet!";
$l_tdr_na       	 = "-";
$l_tdr_cargo    	 = "Kaup";
$l_tdr_none     	 = "Pole";
$l_tdr_colonists         = "kolonistid";
$l_tdr_fighters 	 = "h&auml;vitajad";
$l_tdr_torps    	 = "torpeedod";
$l_tdr_escooped 	 = "[tdr_dist_triptime] k&auml;iku,<br>genereerib [tdr_dist_scooped] energiat";
$l_tdr_warp     	 = "Varp";
$l_tdr_turns    	 = "k&auml;iku";
$l_tdr_way      	 = "-suunaline";
$l_tdr_ways     	 = "-suunaline";
$l_tdr_edit     	 = "Muuda";
$l_tdr_del      	 = "Kustuta";
$l_tdr_nowlink1 	 = "Sektorist [tdr_src_sector_id] sektorisse [tdr_dest_sector_id] ei ole varp-koridori.";
$l_tdr_nowlink2 	 = "Sektorist [tdr_dest_sector_id] sektorisse [tdr_src_sector_id] ei ole varp-koridori.";
$l_tdr_sportissrc        = "Kui alguspunkt on keskjaam, peab l&otilde;pp-punktiks olema planeet.";
$l_tdr_notownplanet      = "Sa ei saa koloniseerida planeeti, mis ei ole Sinu v&otilde;i Su liidu oma.";
$l_tdr_planetisdest      = "Kui l&otilde;pp-punktiks on planeet, peab alguspunktiks olema keskjaam.";
$l_tdr_samecom 		 = "Sa ei saa teha kaubateed sadamate vahele, mis m&uuml;&uuml;vad sama kaupa.";
$l_tdr_sportcom 	 = "Sa ei saa m&uuml;&uuml;a planeedi kaupa keskjaamas.";
$l_tdr_editerr  	 = "Viga muutmisel: andmebaasis ei ole seda kaubateed";
$l_tdr_maxtdr   	 = "Sa oled juba loonud lubatud maksimaalse arvu kaubateid.";
$l_tdr_createnew         = "Loo uus ";
$l_tdr_editinga 	 = "Muuda";
$l_tdr_traderoute        = "kaubatee";
$l_tdr_unnamed  	 = "Nimetu";
$l_tdr_cursector         = "Sa oled praegu sektoris";
$l_tdr_selspoint         = "Vali alguspunkt:";
$l_tdr_port     	 = "Sadam";
$l_tdr_insector 	 = "sektoris";
$l_tdr_selendpoint       = "Vali l&otilde;pp-punkt";
$l_tdr_selmovetype       = "Vali liikumise t&uuml;&uuml;p";
$l_tdr_realspace         = "Avakosmos&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
$l_tdr_selcircuit        = "Vali &uuml;hendus";
$l_tdr_oneway   	 = "&Uuml;hesuunaline";
$l_tdr_errnotvalidport   = "Viga: l&auml;htesadam [tdr_port_id] ei ole korrektne.";
$l_tdr_bothways 	 = "Kahesuunaline";
$l_tdr_create   	 = "Loo";
$l_tdr_modify   	 = "Muuda";
$l_tdr_returnmenu        = "Vajuta <a href=traderoute.php>siia</a> et minna kaubateede men&uuml;&uuml;sse.";
$l_tdr_errnotvalidport   = "Viga: l&auml;htesadam [tdr_port_id] ei ole korrektne.";
$l_tdr_errnoport         = "Viga: sektoris [tdr_port_id] ei ole sadamat.";
$l_tdr_errnosrc    	 = "Viga: l&auml;hteplaneeti ei ole.";
$l_tdr_errnotownnotsell  = "Viga: planeet [tdr_source_name] sektoris [tdr_source_sector_id] ei kuulu Sulle ja see planeet ei m&uuml;&uuml; ka kaupu.";
$l_tdr_errnotvaliddestport= "Viga: l&otilde;ppsadam [tdr_port_id] ei ole korrektne.";
$l_tdr_errnoport2        = "Viga: sektoris [tdr_port_id] ei ole sadamat.";
$l_tdr_errnodestplanet   = "Viga: sihtplaneeti ei ole.";
$l_tdr_errnotownnotsell2 = "Viga: planeet [tdr_dest_name] sektoris [tdr_dest_sector_id] ei kuulu Sulle ja see planeet ei m&uuml;&uuml; ka kaupu.";
$l_tdr_newtdrcreated     = "Uus kaubatee loodud!";
$l_tdr_tdrmodified       = "Kaubatee muudetud!";
$l_tdr_doesntexist       = "Seda kaubateed ei eksisteeri!";
$l_tdr_notowntdr         = "See kaubatee ei kuulu Sulle!";
$l_tdr_tdrdeleted        = "Kaubatee kustutatud.";
$l_tdr_globalset         = "Kaubatee &uuml;ldised seaded";
$l_tdr_tdrsportsrc       = "Kaubateedel, mille l&auml;htepunkt on keskjaam, v&otilde;tta pardale";
$l_tdr_tdrescooped       = "Avakosmoses genereeritud energia";
$l_tdr_trade    	 = "m&uuml;&uuml;a maha";
$l_tdr_keep    	 	 = "hoida alles";
$l_tdr_save    	 	 = "Salvesta";
$l_tdr_globalsetsaved    = "Kaubateede &uuml;ldised seaded salvestatud.";
$l_tdr_engagenonexist    = "&Uuml;ritasid liikuda olematul kaubateel!";
$l_tdr_invalidspoint     = "L&auml;htesadam ei ole korrektne!";
$l_tdr_inittdr  	 = "Sa ei ole sektoris [tdr_source_id]! Sa pead olema l&auml;htesektoris enne kaubateele asumist!";
$l_tdr_invalidsrc        = "L&auml;hteplaneet ei ole korrektne!";
$l_tdr_inittdrsector     = "Sa ei oel sektoris [tdr_source_sector_id]! Sa pead olema l&auml;htesektoris enne kaubateele asumist!";
$l_tdr_notyourplanet     = "Planeet [tdr_source_name] sektoris [tdr_source_sector_id] ei kuulu Sulle!";
$l_tdr_invalidssector    = "L&auml;htesektor ei ole korrektne!";
$l_tdr_invaliddport      = "Sihtsadam ei ole korrektne!";
$l_tdr_invaliddplanet    = "L&otilde;pp-planeet ei ole korrektne!";
$l_tdr_invaliddsector    = "L&auml;htesektor ei ole korrektne!";
$l_tdr_moreturnsneeded   = "See kaubatee vajab [tdr_dist_triptime] k&auml;igu olemasolu. Sul on ainult [tdr_playerinfo_turns] k&auml;iku j&auml;rgi.";
$l_tdr_tdrhostdef        = "Sa ei saa kaubelda sektorite vahel, milles on vaenulikud j&otilde;ud. Sa pead enne sektori kaitsed h&auml;vitama.";
$l_tdr_globalsetbuynothing= "Su &uuml;ldised kaubateede seaded  ei lase millegagi kaubelda! Sa ainult kaotad k&auml;ike selle kaubateega!";
$l_tdr_nosrcporttrade    = "L&auml;htesadamas ei ole lubatud kaubelda.";
$l_tdr_tradesrcportoutsider= "V&otilde;&otilde;rastel ei ole lubatud l&auml;htesadamas kaubelda.";
$l_tdr_nodestporttrade   = "L&otilde;ppsadamas ei ole lubatud kaubelda.";
$l_tdr_tradedestportoutsider= "V&otilde;&otilde;rastel ei ole lubatud l&otilde;ppsadamas kaubelda.";
$l_tdr_tdrres  		 = "Kauplemise tulemused";
$l_tdr_bought  		 = "Pardale v&otilde;eti";
$l_tdr_nothingtotrade    = "Pole millegagi kaubelda";
$l_tdr_sold   	  	 = "M&uuml;&uuml;di";
$l_tdr_ore    		 = "maaki";
$l_tdr_portisfull        = "Sadam on t&auml;is";
$l_tdr_goods    	 = "tarbekaupa";
$l_tdr_organics 	 = "orgaanikat";
$l_tdr_energy   	 = "energiat";
$l_tdr_portisempty       = "Sadam on t&uuml;hi";
$l_tdr_loaded   	 = "pardale v&otilde;etud";
$l_tdr_nothingtoload     = "Pole midagi pardale v&otilde;tta";
$l_tdr_scooped  	 = "Genereeriti";
$l_tdr_dumped   	 = "Maha laeti";
$l_tdr_planetisovercrowded= "Planeet on &uuml;lerahvastatud";
$l_tdr_nothingtodump     = "Pole midagi maha laadida";
$l_tdr_onlyonewaytdr     = "&Uuml;hesuunaline kaubatee, ei teinud midagi";
$l_tdr_profit 		 = "Kasum";
$l_tdr_cost   		 = "Kulu";
$l_tdr_totalprofit       = "<BR>Kogukasum";
$l_tdr_totalcost         = "<BR>Kogukulu";
$l_tdr_credits  	 = "Raha";
$l_tdr_turnsused         = "K&auml;ike kasutati";
$l_tdr_turnsleft         = "K&auml;ike on j&auml;rgi";
$l_tdr_notowner = "See kaubatee ei kuulu Sulle";

// IGB.php

$l_igb_credit_symbol = "$";
$l_igb_title    = "Intergalaktiline Pank";
$l_igb_humor    = "IGB, Su unistuste t&auml;itja";
$l_igb_malfunction      = "See IGB pangaterminal ei t&ouml;&ouml;ta. Intergalaktiline Pank vabandab v&otilde;imalike ebameeldivuste p&auml;rast.";
$l_igb_quit     = "V&auml;lju";
$l_igb_login    = "Login";
$l_igb_welcometoigb     = "Tere tulemast Intergalaktilise Panga terminali";
$l_igb_accountholder    = "Konto omanik";
$l_igb_shipaccount      = "Laeva konto";
$l_igb_igbaccount       = "IGB konto";
$l_igb_operations       = "Vali tehing";
$l_igb_withdraw = "V&auml;ljamakse";
$l_igb_deposit  = "Deposiit";
$l_igb_transfer = "&Uuml;lekanne";
$l_igb_back     = "Tagasi";
$l_igb_logout   = "Logi v&auml;lja";
$l_igb_withdrawfunds    = "Raha v&auml;ljamakse";
$l_igb_fundsavailable   = "Raha kontol";
$l_igb_selwithdrawamount        = "Palun vali v&auml;ljamakse suurus";
$l_igb_depositfunds     = "Raha sissemakse";
$l_igb_seldepositamount = "Palun vali deposiidi suurus";
$l_igb_transfertype     = "&Uuml;lekande t&uuml;&uuml;p";
$l_igb_toanothership    = "Teisele laevale";
$l_igb_shiptransfer     = "&Uuml;lekanne laevale";
$l_igb_fromplanet       = "&Uuml;helt planeedilt teisele";
$l_igb_unnamed  = "Nimetu";
$l_igb_in       = "sektoris";
$l_igb_none     = "Pole";
$l_igb_destination      = "Sihtpunkt";
$l_igb_planettransfer   = "&Uuml;lekanne planeedile";
$l_igb_sendyourself     = "Sa ei saa endale raha &uuml;le kanda!";
$l_igb_unknowntargetship        = "Tundmatu sihtlaev!";
$l_igb_min_turns        = "M&auml;ngija [igb_target_char_name] peab olema kulutanud v&auml;hemalt [igb_min_turns] k&auml;iku enne, kui ta raha vastu saab v&otilde;tta.";
$l_igb_min_turns2       = "Sa pead olema kulutanud v&auml;hemalt [igb_min_turns] k&auml;iku enne, kui Sa raha &uuml;le v&otilde;id kanda.";
$l_igb_mustwait = "Sa oled juba teinud m&auml;ngijale [igb_target_char_name] &uuml;lekande viimase [igb_trate] minuti jooksul. Sa pead ootama veel [igb_difftime] minutit enne, kui Sa v&otilde;id sellele m&auml;ngijale uue &uuml;lekande teha.";
$l_igb_maxtransfer      = "Maksimaalne lubatav &uuml;lekande suurus";
$l_igb_unlimited        = "Piiramatu";
$l_igb_maxtransferpercent       = "Max &uuml;lekande suurus ([igb_percent]% Su impeeriumi v&auml;&auml;rtusest)";
$l_igb_recipient        = "Raha saaja";
$l_igb_seltransferamount        = "Palun vali &uuml;lekande suurus";
$l_igb_transferrate     = "Praegune &uuml;lekandetasu on [igb_num_percent]% &uuml;lekande suurusest. See v&otilde;etakse &uuml;lekandel automaatselt maha.";
$l_igb_errplanetsrcanddest      = "Planeet ei v&otilde;i olla samaaegselt nii l&auml;hte- kui sihtpunkt.";
$l_igb_errunknownplanet = "Andmebaasi viga: tundmatu planeet!";
$l_igb_errnotyourplanet = "Sa ei saa kanda raha planeedile/planeedilt, mis Sulle ei kuulu.";
$l_igb_srcplanet        = "L&auml;he -> Planeet";
$l_igb_destplanet       = "Siht -> Planeet";
$l_igb_transferrate2     = "Praegune &uuml;lekandetasu on [igb_num_percent]% &uuml;lekande suurusest. See v&otilde;etakse &uuml;lekandel automaatselt maha.";
$l_igb_errsendyourself  = "Sa ei saa endale raha &uuml;le kanda!";
$l_igb_min_turns3        = "M&auml;ngija [igb_target_char_name] peab olema kulutanud v&auml;hemalt [igb_min_turns] k&auml;iku enne, kui ta raha vastu saab v&otilde;tta.";
$l_igb_min_turns4       = "Sa pead olema kulutanud v&auml;hemalt [igb_min_turns] k&auml;iku enne, kui Sa raha &uuml;le v&otilde;id kanda.";
$l_igb_mustwait2 = "Sa oled juba teinud m&auml;ngijale [igb_target_char_name] &uuml;lekande viimase [igb_trate] minuti jooksul. Sa pead ootama veel [igb_difftime] minutit enne, kui Sa v&otilde;id sellele m&auml;ngijale uue &uuml;lekande teha.";
$l_igb_invalidtransferinput     = "Vigane v&auml;&auml;rtus.";
$l_igb_nozeroamount     = "&Uuml;lekande suurus ei v&otilde;i olla null.";
$l_igb_notenoughcredits = "Sul ei ole selle tehingu jaoks piisavalt raha.";
$l_igb_amounttoogreat   = "Sisestatud summa on suurem, kui Su lubatud maksimum.";
$l_igb_transfersuccessful       = "&Uuml;lekanne sooritatud";
$l_igb_creditsto        = " raha on &uuml;le kantud m&auml;ngijale";
$l_igb_transferamount   = "&Uuml;lekande summa";
$l_igb_transferfee      = "&Uuml;lekande tasu";
$l_igb_amounttransferred        = "&Uuml;le kantud summa";
$l_igb_notenoughcredits2        = "L&auml;hteplaneedil ei ole nii palju raha.";
$l_igb_to       = "--&gt;";
$l_igb_ctransferredfrom = " raha on &uuml;lekantud m&auml;ngijalt";
$l_igb_invaliddepositinput      = "Vigane v&auml;&auml;rtus.";
$l_igb_nozeroamount2    = "Deposiidi suurus ei tohi olla null.";
$l_igb_operationsuccessful      = "&Uuml;lekanne sooritatud";
$l_igb_creditstoyou     = "raha on Su IGB kontole &uuml;le kantud.";
$l_igb_accounts = "Kontoseis";
$l_igb_invalidwithdrawinput     = "Vigane v&auml;&auml;rtus.";
$l_igb_nozeroamount3    = "V&auml;ljamakse suurus ei tohi olla null.";
$l_igb_creditstoyourship        = "raha on Su laevale &uuml;le kantud.";
$l_igb_igberrreport     = "IGB Veateade";
$l_igb_source   = "L&auml;he";
$l_igb_loans = "Laenud";
$l_igb_loanstatus = "Laenude seis";
$l_igb_currentloan = "Hetkel laenatud summa";
$l_igb_maxloanpercent = "Maksimaalne lubatud laen ([igb_percent]% Su impeeriumi v&auml;&auml;rtusest)";
$l_igb_loanamount = "Sisesta laenatav summa";
$l_igb_borrow = "Laena";
$l_igb_loanrates     = "Iga v&otilde;etud laenu eest tuleb &uuml;hekordselt tasuda [factor]% laenatavast summast teenustasuks. Lisaks v&otilde;etakse igal k&auml;igul [interest]% intressi seni, kuni laen on tagasi makstud.";
$l_igb_invalidamount = "Sa sisestasid vigase koguse.";
$l_igb_notwoloans = "Sa ei v&otilde;i v&otilde;tta uut laenu ilma eelmist tagasi maksmata.";
$l_igb_loantoobig = "Sa ei v&otilde;i laenata nii suurt kogust.";
$l_igb_takenaloan = "Laen v&otilde;etud";
$l_igb_loancongrats = "&Otilde;nnitlused! Sa oled just v&otilde;tnud laenu k&otilde;ige s&otilde;bralikumast panganduss&uuml;steemist galaktikas!";
$l_igb_loantransferred = "Su laeva kontole &uuml;le kantud summa";
$l_igb_loanfee = "Teenustasu";
$l_igb_amountowned = "Kogu IGB-le v&otilde;lgnetav summa";
$l_igb_loanreminder = "S&otilde;bralik meeldetuletus: kui Sa ei ole [hours] tunni ja [mins] minuti jooksul oma laenu t&auml;ielikult tagasi maksnud, oleme me sunnitud Su laeva konto arestima.<br><br>\"IGB, Su unistuste t&auml;itja\"";
$l_igb_loantimeleft = "Sul on laenu t&auml;ielikuks tasumiseks aega";
$l_igb_loanlate = "Tagasimakse on hilinenud!";
$l_igb_repayamount = "Sisesta tagasimakstav summa";
$l_igb_repay = "Maksa&nbsp;tagasi";
$l_igb_notrepay = "Sul ei ole &uuml;htegi laenu, mida tagasi maksta";
$l_igb_notenoughrepay = "Su laeva kontol ei ole piisavalt raha, et seda tehingut sooritada.";
$l_igb_payloan = "Tagasimakse";
$l_igb_loanthanks = "Su tagasimakse on vastu v&otilde;etud. Ait&auml;h, et kasutasid IGB teenuseid.";
$l_igb_credsconsol = "L&auml;he -> raha kokkkukogumiseks";
$l_igb_transferrate3     = "Kokku kogumise tasu on [igb_num_percent]% kogusummast. See v&otilde;etakse automaatselt maha kogutud summalt. &Uuml;lekanne kulutab &uuml;he k&auml;igu iga [nbplanets] tehinguga seotud planeedi kohta.";
$l_igb_currentpl = "Raha planeedil";
$l_igb_consolrates = "Sa v&otilde;id m&auml;&auml;rata &uuml;lekande piirid. Planeedid, millel on v&auml;hem raha kui Minimaalne v&otilde;i millel on rohkem raha kui Maksimaalne j&auml;etakse tehingust v&auml;lja. Sisesta 0, kui Sa ei soovi piiri seada";
$l_igb_minimum = "Minimaalne";
$l_igb_maximum = "Maksimaalne";
$l_igb_planetconsolidate = "Raha kokku kogumine";
$l_igb_compute = "Arvuta";
$l_igb_plaffected = "Tehinguga seotud planeete";
$l_igb_turncost = "K&auml;ike kulub";
$l_igb_consolidate = "Kogu kokku";
$l_igb_conspl = "Kogu raga &uuml;hele planeedile";
$l_igb_notenturns = "Sul ei ole piisavalt k&auml;ike, et seda teha";

// combat.php

$l_cmb_atleastoneturn   = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et planeeti r&uuml;nnata.";
$l_cmb_shipenergybb     = "Laeva energia enne lasereid";
$l_cmb_shipenergyab     = "Laeva energia p&auml;rast lasereid";
$l_cmb_shipenergyas     = "Laeva energia p&auml;rast energiakilpi";
$l_cmb_shiptorpsbtl     = "Laeva torpeedod enne laskmist";
$l_cmb_shiptorpsatl     = "Laeva torpeedod p&auml;rast laskmist";
$l_cmb_planettorpdamage = "Planeedi torpeedode purustus";
$l_cmb_attackertorpdamage       = "Laeva torpeedode purustus";
$l_cmb_beams    = "Laserid";
$l_cmb_fighters = "H&auml;vitajad";
$l_cmb_shields  = "Energiakilp";
$l_cmb_torps    = "Torpeedod";
$l_cmb_torpdamage       = "Torpeedode purustus";
$l_cmb_armor    = "Soomus";
$l_cmb_you      = "Laev";
$l_cmb_planet   = "Planeet";
$l_cmb_combatflow       = "Lahingu k&auml;ik";
$l_cmb_defender = "Kaitsja";
$l_cmb_attackingplanet  = "Planeedi r&uuml;ndamine sektoris";
$l_cmb_youfireyourbeams = "Sinu laserid tulistasid";
$l_cmb_defenselost      = "Planeedi kaitse kaotas [cmb_planetfighters] h&auml;vitajat Sinu laserite r&uuml;nnakus";
$l_cmb_defenselost2     = "Planeedi kaitse kaotas [cmb_attackerbeams] h&auml;vitajat, aga neid on planeedil veel!";
$l_cmb_planetarybeams   = "Planeedi laserid purustasid [cmb_temp] Sinu h&auml;vitajat";
$l_cmb_planetarybeams2   = "Planeedi laserid purustasid [cmb_planetbeams] Sinu h&auml;vitajat";
$l_cmb_youdestroyedplanetshields        = "Su laserid purustasid planeedi energiakilbi";
$l_cmb_beamsexhausted   = "Sa purustasid planeedi energiakilbi [cmb_attackerbeams] punkti ulatuses enne, kui Su laserid otsa said";
$l_cmb_breachedyourshields      = "Planeedi laserid purustasid Su energiakilbi";
$l_cmb_destroyedyourshields     = "Planeedi laserid purustasid Su energiakilbi [cmb_planetbeams] punkti ulatuses";
$l_cmb_breachedyourarmor        = "Planeedi laserid purustasid Su soomuse";
$l_cmb_destroyedyourarmor       = "Planeedi laserid purustasid Su soomuse [cmb_planetbeams] punkti ulatuses";
$l_cmb_torpedoexchangephase     = "Torpeedode r&uuml;nnak";
$l_cmb_nofightersleft   = "Su torpeedod purustasid [cmb_planetfighters] planeedi h&auml;vitajat, planeedil ei ole rohkem h&auml;vitajaid";
$l_cmb_youdestroyfighters       = "Su torpeedod purustasid [cmb_attackertorpdamage] planeedi h&auml;vitajat";
$l_cmb_planettorpsdestroy       = "Planeedi torpeedod purustasid [cmb_temp] Sinu h&auml;vitajat";
$l_cmb_planettorpsdestroy2      = "Planeedi torpeedod purustasid [cmb_planettorpdamage] Sinu h&auml;vitajat";
$l_cmb_torpsbreachedyourarmor   = "Planeedi torpeedod purustasid Su soomuse";
$l_cmb_planettorpsdestroy3      = "Planeedi torpeedod purustasid Su soomuse [cmb_planettorpdamage] punkti ulatuses";
$l_cmb_youdestroyedallfighters  = "Su torpeedod purustasid k&otilde;ik planeedi h&auml;vitajad";
$l_cmb_youdestroyplanetfighters = "Su torpeedod purustasid [cmb_attackertorpdamage] planeedi h&auml;vitajat";
$l_cmb_fightercombatphase       = "H&auml;vitajate r&uuml;nnak";
$l_cmb_youdestroyedallfighters2  = "Su h&auml;vitajad purustasid k&otilde;ik planeedi h&auml;vitajad.";
$l_cmb_youdestroyplanetfighters2        = "Su h&auml;vitajad purustasid [cmb_attackerfighters] planeedi h&auml;vitajat";
$l_cmb_allyourfightersdestroyed = "K&otilde;ik Su h&auml;vitajad on purustatud";
$l_cmb_fightertofighterlost     = "Sa kaotasid h&auml;vitajate lahingus [cmb_planetfighters] h&auml;vitajat";
$l_cmb_youbreachedplanetshields = "Su h&auml;vitajad purustasid planeedi energiakilbi";
$l_cmb_shieldsremainup  = "Su h&auml;vitajad purustasid planeedi energiakilbi [cmb_attackerfighters] punkti ulatuses, aga kilp ei ole t&auml;ielikult purustatud";
$l_cmb_fighterswarm     = "Planeedi h&auml;vitajad r&uuml;ndasid Su laeva ja purustasid Su soomuse";
$l_cmb_swarmandrepel    = "Planeedi h&auml;vitajad r&uuml;ndasid Su laeva, aga Su soomus suutis neid t&otilde;rjuda";
$l_cmb_engshiptoshipcombat      = "<B>&Uuml;leminek laev-laev lahingule.</B>";
$l_cmb_shipdock = "<B>Planeedi kosmodroomil oli [cmb_shipsonplanet] laeva!</B>";
$l_cmb_approachattackvector     = "sattus tulejoonele";
$l_cmb_noshipsdocked    = "Planeedi kosmodroomil ei ole &uuml;htegi laeva.";
$l_cmb_yourshipdestroyed        = "Su laev on h&auml;vitatud!";
$l_cmb_escapepod        = "&Otilde;nneks oli Sul p&auml;&auml;stekapsel!";
$l_cmb_finalcombatstats = "Lahingu l&otilde;ppstatistika";
$l_cmb_youlostfighters  = "Sa kaotasid [cmb_fighters_lost] h&auml;vitajat oma [cmb_playerinfo_ship_fighters]-st h&auml;vitajast.";
$l_cmb_youlostarmorpoints       = "Sa kaotasid oma [cmb_playerinfo_armour_pts]-punktilisest soomusest [cmb_armor_lost] punkti, Sul j&auml;i j&auml;rgi [cmb_attackerarmor] soomusepunkti.";
$l_cmb_energyused       = "Sa kasutasid oma [cmb_playerinfo_ship_energy]-st energiast &auml;ra [cmb_energy_lost] &uuml;hikut.";
$l_cmb_planetdefeated   = "Planeet alistatud";
$l_cmb_citizenswanttodie        = "Selle planeedi elanikud otsustasid, et nad ennemini surevad, kui teenivad sellist <i>luuserit</i>, nagu Sina. Nad puurisid hiidlaseriga augu l&auml;bi planeedi pinnase. Sul j&auml;i napilt aega, et p&otilde;geneda planeedi orbiidile enne, kui kogu planeet ujutus &uuml;le sulalaavaga.";
$l_cmb_youmaycapture    = "Sa v&otilde;id planeedi <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>h&otilde;ivata</a> v&otilde;i selle lihtsalt <a href=main.php>kaitseta j&auml;tta</a>.";
$l_cmb_youmaycapture2   = "Sa v&otilde;id planeedi <a href=planet.php?planet_id=[cmb_planetinfo_planet_id]&command=capture>h&otilde;ivata</a> v&otilde;i selle lihtsalt <a href=main.php>kaitseta j&auml;tta</a>.";
$l_cmb_planetnotdefeated        = "Planeet ei ole alistatud";
$l_cmb_planetstatistics = "Planeedi statistika";
$l_cmb_fighterloststat  = "H&auml;vitajaid kaotatud: [cmb_fighters_lost]  [cmb_planetinfo_fighters]-st ([cmb_planetfighters] j&auml;i j&auml;rgi)";
$l_cmb_energyleft       = "Energiat j&auml;i j&auml;rgi";
$l_cmb_startingstats    = "Algusstatistika";
$l_cmb_statattackerbeams        = "R&uuml;ndaja laserid";
$l_cmb_statattackerfighters     = "R&uuml;ndaja h&auml;vitajad";
$l_cmb_statattackershields      = "R&uuml;ndaja energiakilp";
$l_cmb_statattackertorps        = "R&uuml;ndaja torpeedod";
$l_cmb_statattackerarmor        = "R&uuml;ndaja soomus";
$l_cmb_statattackertorpdamage   = "R&uuml;ndaja torpeedode purustus";
$l_cmb_isattackingyou   = "r&uuml;ndas Sind";
$l_cmb_beamexchange     = "Laserite r&uuml;nnak";
$l_cmb_beamsdestroy     = "Su laserid purustasid [cmb_lost] h&auml;vitajat";
$l_cmb_beamsdestroy2    = "Su laserid purustasid [cmb_attackerbeams] h&auml;vitajat, aga neid on veel tulemas";
$l_cmb_nobeamsareleft   = "Sule ei ole enam lasereid j&auml;rgi, et purustada r&uuml;ndavaid h&auml;vitajaid!";
$l_cmb_beamshavenotarget        = "Su laseritel pole enam &uuml;htegi h&auml;vitajat tulistada";
$l_cmb_fighterdestroyedbybeams  = "Laev [cmb_targetinfo_ship_name] purustas [cmb_lost] Sinu h&auml;vitajat oma laseritega<BR>";
$l_cmb_beamsdestroystillhave    = "Laev [cmb_targetinfo_ship_name] purustas [cmb_targetbeams] Sinu h&auml;vitajat oma laseritega, aga Sul on veel [cmb_attackerfighters] h&auml;vitajat j&auml;rgi";
$l_cmb_fighterunhindered        = "Su h&auml;vitajad r&uuml;ndasid takistamatult - vastasel ei olnud enam lasereid.";
$l_cmb_youhavenofightersleft    = "Sul ei ole enam h&auml;vitajaid, millega r&uuml;nnata";
$l_cmb_breachedsomeshields      = "Su laserid purustasid laeva [cmb_targetinfo_ship_name] energiakilbi";
$l_cmb_shieldsarehitbybeams     = "Laeva [cmb_targetinfo_ship_name] energiakilp sai [cmb_attackerbeams] punkti ulatuses vigastada, kui Su laserid seda r&uuml;ndasid";
$l_cmb_nobeamslefttoattack      = "Sul ei ole enam lasereid j&auml;rgi, et laeva [cmb_targetinfo_ship_name] energiakilpi r&uuml;nnata";
$l_cmb_yourshieldsbreachedby    = "Laeva [cmb_targetinfo_ship_name] laserid purustasid Su energiakilbi";
$l_cmb_yourshieldsarehit        = "Laeva [cmb_targetinfo_ship_name] laserid purustasid Su energiakilbi [cmb_targetbeams] punkti ulatuses.";
$l_cmb_hehasnobeamslefttoattack = "Laeval [cmb_targetinfo_ship_name] ei ole enam lasereid j&auml;rgi, et Su energiakilpi r&uuml;nnata";
$l_cmb_yourbeamsbreachedhim     = "Su laserid purustasid laeva [cmb_targetinfo_ship_name] soomuse";
$l_cmb_yourbeamshavedonedamage  = "Su laserid purustasid laeva [cmb_attackerbeams] soomuse [cmb_targetinfo_ship_name] punkti ulatuses";
$l_cmb_nobeamstoattackarmor     = "Sul ei ole enam lasereid j&auml;rgi, et laeva [cmb_targetinfo_ship_name] soomust r&uuml;nnata";
$l_cmb_yourarmorbreachedbybeams = "Laeva [cmb_targetinfo_ship_name] laserid purustasid Su soomuse";
$l_cmb_yourarmorhitdamaged      = "Laeva [cmb_targetinfo_ship_name] laserid purustasid Su soomuse [cmb_targetbeams] punkti ulatuses";
$l_cmb_torpedoexchange  = "Torpeedode r&uuml;nnak";
$l_cmb_hehasnobeamslefttoattackyou      = "Laeval [cmb_targetinfo_ship_name] ei ole enam lasereid j&auml;rgi, et Su soomust r&uuml;nnata";
$l_cmb_yourtorpsdestroy = "Su torpeedod purustasid [cmb_lost] laeva [cmb_targetinfo_ship_name] h&auml;vitajat";
$l_cmb_yourtorpsdestroy2        = "Su torpeedod purustasid [cmb_attackertorpdamage] laeva [cmb_targetinfo_ship_name] h&auml;vitajat";
$l_cmb_youhavenotorpsleft       = "Sul ei ole enam torpeedosid j&auml;rgi, et r&uuml;nnata laeva [cmb_targetinfo_ship_name] h&auml;vitajaid.";
$l_cmb_hehasnofighterleft       = "Laeval [cmb_targetinfo_ship_name] ei ole enam h&auml;vitajaid, mida Su torpeedod r&uuml;nnata v&otilde;iksid";
$l_cmb_torpsdestroyyou  = "Laeva [cmb_targetinfo_ship_name] torpeedod purustasid [cmb_lost] Sinu h&auml;vitajat";
$l_cmb_someonedestroyedfighters = "Laeva [cmb_targetinfo_ship_name] torpeedod purustasid [cmb_targettorpdmg] Sinu h&auml;vitajat";
$l_cmb_hehasnotorpsleftforyou   = "Laeval [cmb_targetinfo_ship_name] ei ole enam torpeedosid, et Su h&auml;vitajaid r&uuml;nnata";
$l_cmb_youhavenofightersanymore = "Sul ei ole enam h&auml;vitajaid, mida laeva [cmb_targetinfo_ship_name] torpeedod purustada saaksid";
$l_cmb_youbreachedwithtorps     = "Su torpeedod purustasid laeva [cmb_targetinfo_ship_name] soomuse";
$l_cmb_hisarmorishitbytorps     = "Su torpeedod purustasid laeva [cmb_targetinfo_ship_name] soomuse [cmb_attackertorpdamage] punkti ulatuses";
$l_cmb_notorpslefttoattackarmor = "Sul ei ole enam torpeedosid, et r&uuml;nnata laeva [cmb_targetinfo_ship_name] soomust";
$l_cmb_yourarmorbreachedbytorps = "Laeva [cmb_targetinfo_ship_name] torpeedod purustasid Su soomuse";
$l_cmb_yourarmorhitdmgtorps     = "Laeva [cmb_targetinfo_ship_name] torpeedod purustasid Su soomuse [cmb_targettorpdmg] punkti ulatuses";
$l_cmb_hehasnotorpsforyourarmor = "Laeval [cmb_targetinfo_ship_name] ei ole enam torpeedosid, et Su soomust r&uuml;nnata";
$l_cmb_fightersattackexchange   = "H&auml;vitajate r&uuml;nnak";
$l_cmb_enemylostallfighters     = "Laev [cmb_targetinfo_ship_name] kaotas k&otilde;ik h&auml;vitajad.";
$l_cmb_helostsomefighters       = "Laev [cmb_targetinfo_ship_name] kaotas [cmb_attackerfighters] h&auml;vitajat.";
$l_cmb_youlostallfighters       = "Sa kaotasid k&otilde;ik h&auml;vitajad.";
$l_cmb_youalsolostsomefighters  = "Sa kaotasid [cmb_targetfighters] h&auml;vitajat.";
$l_cmb_hehasnofightersleftattack        = "Laeval [cmb_targetinfo_ship_name] ei ole enam h&auml;vitajaid, mida Su h&auml;vitajad r&uuml;nnata v&otilde;iksid";
$l_cmb_younofightersattackleft  = "Sul ei ole enam h&auml;vitajaid j&auml;rgi, et r&uuml;nnata laeva [cmb_targetinfo_ship_name] h&auml;vitajaid";
$l_cmb_youbreachedarmorwithfighters     = "Su h&auml;vitajad purustasid laeva [cmb_targetinfo_ship_name] soomuse";
$l_cmb_youhitarmordmgfighters   = "Su h&auml;vitajad purustasid laeva [cmb_targetinfo_ship_name] soomuse [cmb_attackerfighters] punkti ulatuses";
$l_cmb_youhavenofighterstoarmor = "Sul ei ole enam h&auml;vitajaid j&auml;rgi, et r&uuml;nnata laeva [cmb_targetinfo_ship_name] soomust";
$l_cmb_hasbreachedarmorfighters = "Laev [cmb_targetinfo_ship_name] purustas Su soomuse oma h&auml;vitajatega";
$l_cmb_yourarmorishitfordmgby   = "Laeva [cmb_targetinfo_ship_name] h&auml;vitajad purustasid Su soomuse [cmb_targetfighters] punkti ulatuses";
$l_cmb_nofightersleftheforyourarmor     = "Laeval [cmb_targetinfo_ship_name] ei ole enam h&auml;vitajaid j&auml;rgi, et r&uuml;nnata Su soomust";
$l_cmb_hehasbeendestroyed       = "<b>Laev [cmb_targetinfo_ship_name] on purustatud!</b>";
$l_cmb_escapepodlaunched        = "H&auml;vivast laevast eraldus p&auml;&auml;stekapsel!";
$l_cmb_yousalvaged      = "Sa said vrakilt k&auml;tte [cmb_salv_ore] &uuml;hikut maaki, [cmb_salv_organics] &uuml;hikut orgaanikat, [cmb_salv_goods] &uuml;hikut tarbekaupa ja [cmb_salvage_rate]% laevast v&auml;&auml;rtusega [cmb_salvage] raha.<BR>Su reiting muutus [cmb_number_rating_change] punkti v&otilde;rra.<BR>";
$l_cmb_youdidntdestroyhim       = "Sa ei purustanud laeva [cmb_targetinfo_ship_name]!";
$l_cmb_shiptoshipcombatstats    = "<B>Laev-laev lahingu tulemused:</B>";

// check_mines.php

$l_chm_youhitsomemines  = "Sa p&otilde;rkasid vastu [chm_roll] miini!";
$l_chm_hehitminesinsector       = "[chm_playerinfo_character_name] p&otilde;rkas vastu [chm_roll] miini sektoris [chm_sector].";
$l_chm_youlostminedeflectors    = "Sa kaotasid [chm_roll] miinit&otilde;rjujat.";
$l_chm_youlostallminedeflectors = "Sa kaotasid k&otilde;ik oma miinit&otilde;rjujad.";
$l_chm_youhadnominedeflectors  = "Sul polnud &uuml;htegi miinit&otilde;rjujat.";
$l_chm_yourshieldshitforminesdmg        = "Su energiakilp sai [chm_mines_left] punkti ulatuses vigastada.";
$l_chm_yourshieldsaredown       = "Su energiakilp l&uuml;litus v&auml;lja!";
$l_chm_youlostallyourshields    = "Sa kaotasid kogu oma energiakilbi!";
$l_chm_yourarmorhitforminesdmg  = "Su soomus sai [chm_mines_left] punkti ulatuses vigastada.";
$l_chm_yourhullisbreached       = "Kogu Su soomus on purustatud!";
$l_chm_hewasdestroyedbyyourmines        = "Su miinid purustasid m&auml;ngija [chm_playerinfo_character_name] sektoris [chm_sector].";
$l_chm_yourshiphasbeendestroyed = "<b>Su laev on purustatud!</b>";
$l_chm_luckescapepod    = "&Otilde;nneks oli Sul p&auml;&auml;stekapsel!";

// check_fighters.php

$l_chf_youretreatback   = "Sa liikusid tagasi oma eelmisesse asukohta";
$l_chf_notenoughcreditstoll     = "Sul ei ole nii palju raha, et tollimaksu tasuda.";
$l_chf_movefailed       = "Liikumine eba&otilde;nnestus.";
$l_chf_youpaidsometoll  = "Sa maksid [chf_tollstring] raha tollimaksu.";
$l_chf_thefightersdetectyou     = "H&auml;vitajad avastasid Su!";
$l_chf_therearetotalfightersindest      = "Sektoris, kuhu Sa liikuda soovid, on [chf_total_sector_fighters] h&auml;vitajat.";
$l_chf_creditsdemanded  = "Nad n&otilde;uavad [chf_number_fighterstoll] raha tollimaksu, et Sind sellesse sektorisse lubada.";
$l_chf_youcanretreat    = "Sa v&otilde;id <BR><INPUT TYPE=RADIO NAME=response VALUE=retreat><B>Tagasi liikuda</B> - see l&auml;heb Sulle lisak&auml;igu maksma.<BR></INPUT>";
$l_chf_inputpay = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=pay><B>Maksta tollimaksu</B> - ja &uuml;kski h&auml;vitaja ei puutu Sind.<BR></INPUT>";
$l_chf_inputfight       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=fight><B>V&otilde;idelda</B> - Sa pead k&otilde;ik sektori h&auml;vitajad &auml;ra v&otilde;itma.<BR></INPUT>";
$l_chf_inputcloak       = "<INPUT TYPE=RADIO NAME=response CHECKED VALUE=sneak><B>Sisse hiilida</B> - kasutad oma radarisegajat ja p&uuml;&uuml;ad h&auml;vitajaid v&auml;ltida.<BR></INPUT>";
$l_chf_go       = "Mine";

// mines.php

$l_mines_title			="Sektori kaitsete paigutamine";
$l_mines_noturn		 	="Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et sektori kaitseid paigutada.";
$l_mines_nopermit		="Siia sektorisse ei ole lubatud sektori kaitseid paigutada.";
$l_mines_nodeploy		="Siia ei saa sektori kaitseid paigutada. Siin on juba mingi tese liidu v&otilde;i m&auml;ngija sektori kaitsed.";
$l_mines_info1			="Sa oled praegu sektoris [sector]. Siin on praegu [mines] miini ja [fighters] h&auml;vitajat.";
$l_mines_info2			="Sul on pardal [mines] miini ehk torpeedot ja [fighters] h&auml;vitajat.";
$l_mines_deploy			="Paiguta";
$l_mines_deployed		="Paigutatud";
$l_mines_att			="r&uuml;nnak";
$l_mines_toll			="toll";
$l_mines_notorps		="Sul ei ole piisavalt torpeedosid.";
$l_mines_nofighters		="Sul ei ole piisavalt h&auml;vitajaid";
$l_mines_dmines			="Paigutasid [mines] miini.";
$l_mines_dfighter		="Paigutasid [fighters] h&auml;vitajat olekusse [mode].";
$l_mines_fmode			="H&auml;vitajate olek:";

//alliance-planets.php

$l_teamplanet_title		="Liidu planeedid";
$l_teamplanet_notally		="Sa ei ole liidus.";
$l_teamplanet_personal		="N&auml;ita personaalseid planeete";
$l_teamplanet_noplanet		="Su liidul ei ole planeete";

$l_feedback_title		="Tagasiside";
$l_feedback_to			="Saaja:";
$l_feedback_from		="Saatja:";
$l_feedback_topi		="Pealkiri:";
$l_feedback_feedback		="Tagasiside";
$l_feedback_message		="Teade:";
$l_feedback_messent		="Tagasiside info saadetud";
$l_feedback_subj		="WTW Feedback";
$l_feedback_info		="Palun saada tagasisidet ainult eesti v&otilde;i inglise keeles."; // gameadmins put all your languages here

// corp.php
$l_corpm_title			="Liidu men&uuml;&uuml;";
$l_corpm_tocorp			="Planeet on n&uuml;&uuml;d liidu planeet!";
$l_corpm_topersonal		="Planeet on n&uuml;&uuml;d isiklik planeet!";
$l_corpm_exploit		="Midagi on v&auml;ga valesti, blerg...";


// login.php login2.php
$l_login_title			="Logi sisse";
$l_login_email			="e-maili aadress:";
$l_login_pw			="Parool:";
$l_login_chooseres		="Ei suuda m&auml;&auml;rata Su ekraani resolutsiooni. Palun vali l&auml;hedasim:";
$l_login_newp			= "Kui Sa oled uus m&auml;ngija, vajuta <A HREF=\"new.php\">siia</A>.";
$l_login_prbs			= "Probleemid?";
$l_login_emailus		= "Kirjuta meile.";
$l_login_sclosed		= "Server on suletud";
$l_login_closed_message		="Server on suletud kuni j&auml;rgmiste teadeteni.";
$l_login_title2			="Sisse logimise teine faas";
$l_login_banned			="<b>M&auml;ngu administraator on Su sellest m&auml;ngust eemaldanud. Sellel serveril Sa enam m&auml;ngida ei saa. K&auml;itu j&auml;rgmine kord paremini.</b>";
$l_login_died			="Su laev h&auml;vitati, aga Su p&auml;&auml;stekapsel s&auml;&auml;stis nii Sind kui Su meeskonda.  Vajuta <A HREF=main.php>siia</A> et j&auml;tkata m&auml;ngu uue laevaga.";
$l_login_newbie			="L&auml;htudes selle kuriteo t&otilde;sidusest ja j&otilde;hkrusest Sinu vastu otsustas F&ouml;deratsioon tasuda Sinu j&auml;&auml;nuste kloonimise kulud. Kahjuks ei anta isegi t&auml;nap&auml;eval kloonidele omandit, v&auml;lja arvatud esmatarbekaubad.  Sind varustati algelise laeva ja v&auml;ikese rahasummaga, et Sul oleks kusagilt alustada. Loodetavasti kujuneb Su uus elu ilusamaks...";
$l_login_newlife		="Vajuta <A HREF=main.php>siia</A> et j&auml;tkata oma uut elu.";
$l_login_looser			="Sul ei olnud p&auml;&auml;stekapslit ja kuna Su areng eelmises elus ei olnud just eriti peadp&ouml;&ouml;ritav, siis keeldus F&ouml;deratsioon Su kloonimisest. Su j&auml;&auml;nused langevad ilmselt m&otilde;nda Musta Auku, et kunagi kusagil mujal uuele elule alus panna... m&otilde;ne miljardi aasta p&auml;rast.<BR><BR> Ehk veab Sul uues m&auml;ngus rohkem...";
$l_login_4gotpw1		= "Parool ei olnud &otilde;ige.<BR><BR>  Kui Sa oled oma parooli unustanud, siis ";
$l_login_4gotpw2		= "ja see saadetakse Sulle e-mailile.<BR><BR>  Vastasel juhul";
$l_login_4gotpw3		= "et uuesti proovida. See &uuml;ritamine kirjutati logisse, aadress";
$l_login_noone			= "Sellist m&auml;ngijat ei ole! - Tee <A HREF=new.php>siin</A> uus m&auml;ngija.";
$l_login_lang = "Keel";
$l_login_settings = "M&auml;ngu parameetrid";
$l_login_change = "Muuda";
///$l_login_forgot_pw = "Unustasid oma parooli? J&auml;ta see lahter t&uuml;hjaks ja vajuta 'Logi sisse'.";

// new.php new2.php
$l_new_title			= "Uue m&auml;ngija loomine";
$l_new_title2			= "Uue m&auml;ngija loomise teine faas";
$l_new_shipname			= "Laeva nimi";
$l_new_pname			= "M&auml;ngija nimi";
$l_new_info			= "Me lubame, et Sinu e-maili aadressi ei jagata (ega m&uuml;&uuml;da) kellelegi. Aadress on vajalik vaid selleks, et server saaks Sulle parooli saata.";
$l_new_closed_message		="M&auml;ng on suletud turniirim&auml;nguks";
$l_new_blank			="e-mail, laeva nimi ega m&auml;ngija nimi ei tohi t&uuml;hjaks j&auml;&auml;da.";
$l_new_inuse			="See e-maili aadress on juba kasutusel.";
$l_new_4gotpw1			="Kui Sa oled oma parooli unustanud,";
$l_new_4gotpw2			="ja see saadetakse Sulle e-mailile.";
$l_new_inusechar		="M&auml;ngija nimi </b>'$character'</b> on juba kasutusel.";
$l_new_inuseship		="Laeva nimi <b>'$shipname'</b> on juba kasutusel.";
$l_new_pwsent			="Parool on saadetud aadressile ${HTTP_POST_VARS['username']}.";
$l_new_login			="et minna sisse logimise men&uuml;&uuml;sse.";
$l_new_err			="Palun mine tagasi v&otilde;i <a href=new.php>vajuta siia</a> ja proovi uuesti.";
$l_new_topic			="Traders parool";
$l_new_message			="Tervitus,\r\n\r\nKeegi aadressilt $ip soovis, et Sulle saadetaks Sinu 'Traders' parool.\r\n\r\nSu parool on: [pass]\r\n\r\nAit&auml;h\r\n\r\n$game_name veebitiim.";

// logout.php

$l_logout_score			="Su praegune skoor on";
$l_logout_text			="[name] on v&auml;lja loginud.  Vajuta <A HREF=index.php>siia</A> et m&auml;ngu tagasi tulla.";

// mail.php

$l_mail_title			="Parooli saatmine";
$l_mail_noplayer		="Sellist m&auml;ngijat ei ole! - Tee <A HREF=new.php>siin</A> uus m&auml;ngija.";
$l_mail_sent			="Parool on saadetud aadressile";
$l_mail_topic			="$game_name parool";
$l_mail_message			="Tervitus,\r\n\r\nKeegi aadressilt $ip soovis saada parooli m&auml;ngule $game_name.\r\n\r\nSu parool on: [pass]\r\n\r\nAit&auml;h\r\n\r\n$game_name veebitiim.";

// global_funcs.php

$l_global_mmenu			="Vajuta <A HREF=main.php>siia</A> et minna peamen&uuml;&uuml;sse.";
$l_global_mlogin		="Vajuta <A HREF=login.php>siia</A> et minna sisse logimise lehele.";
$l_global_needlogin		="Sa pead enne sisse logima, vajuta <A HREF=login.php>siia</A>.";
$l_global_died			="M&auml;ngija on H&Auml;VITATUD! <a href=log.php>Siin</a> on kirjas, mis juhtus.<BR><BR>Ehk on Sul j&auml;rgmisel korral rohkem &otilde;nne! ";
$l_global_warzone		="Tsoon muutus s&otilde;jatsooniks!";
$l_global_nzone			="Tsoon on neutraalne.";
$l_global_team			="Tsoon kuulub n&uuml;&uuml;d liidule";
$l_global_player		="Tsoon kuulub n&uuml;&uuml;d m&auml;ngijale";

// texts for the news flashes

$l_news_planets		  = " planeeti";
$l_news_cols		      = " miljonit kolonisti";
$l_news_p_headline = "M&auml;ngija [player] impeeriumis on ";

$l_killheadline=" hukkus";
$l_news_killed = "M&auml;ngija [name] hukkus t&auml;na traagilises &otilde;nnetuses. Kui kangelaslik - kapten [name] oli viimane meeskonnaliige oma laeva pardal, kui ta avastas, et temale enam p&auml;&auml;stekapslis kohta ei ole. Puhaku ta rahus!";
$l_news_p_text5		= "M&auml;ngija [name] kasvavas impeeriumis on juba viis planeeti. BNN j&auml;lgib [name] m&auml;ngija tegevust tulevikus veelgi t&auml;helepanelikumalt!";
$l_news_p_text10		= "M&auml;ngija [name] kasvav impeerium kontrollib juba k&uuml;mmet planeeti. BNN arvab, et M&auml;ngija [name] edasine ekspansioon v&otilde;ib viia s&otilde;jategevuseni!";
$l_news_p_text25		= "M&auml;ngija [name] hiiglaslikku impeeriumisse kuulub juba 25 planeeti. Intervjuus BNN-le &uuml;tles m&auml;ngija [name], et tulevikus ta ilmselt aeglustab koloniseerimistempot!";
$l_news_p_text50		= "M&auml;ngija [name] hirmu&auml;ratavalt suur impeerium koosneb juba 50-st planeedist &uuml;le terve galaktika ja kogub hirmu&auml;ratavat j&otilde;udu! &Uuml;ks BNN reporteritest on t&auml;heldanud, et m&auml;ngija [name] arendab oma laeva eesm&auml;rgiga alustada hiiglaslikku s&otilde;da. Intervjuus &uuml;tles m&auml;ngija [name], et arendus on vaid kaitseotstarbeline!";
$l_news_c_text25		= "M&auml;ngija [name] kasvavasse impeeriumisse kuulub juba &uuml;le 25 miljoni kolonisti. Tulevikus j&auml;lgib BNN m&auml;ngija [name] tegevust &uuml;ha hoolikamalt, aga on ilmne, et s&uuml;ndimus hakkab kiirelt kasvama!";
$l_news_c_text100		= "M&auml;ngija [name] paisuvas impeeriumis on juba ligi 100 miljonit kolnisti. P&auml;rast s&uuml;ndivuse plahvatuslikku t&otilde;usu paistavad m&auml;ngija [name] kolooniad peredele v&auml;ga sobilikud elukohad olevat!";
$l_news_c_text500		= "M&auml;ngija [name] suurimpeeriumis on 500 miljonit elanikku. [name] &Uuml;tles intervjuus BNN-le, et koloniseerimine on alles alanud...";
$l_news_c_text1000		= "M&auml;ngija [name] hiidimpeeriumis on juba miljard (!) kolonisti. BNN reporterid kahtlustavad, et [name] kasutab mingit kummalist kloonimismehhanismi, mis v&otilde;imaldab tal luua uusi kolooniaid suurtes kogustes. Sellise arvu kolonistide juures on m&auml;ngija [name] tulud meeletud. BNN loodab, et [name] ei kuluta kogu oma raha s&otilde;dadele.";

// Options.php

$l_opt_title = "Seaded";
$l_opt_chpass = "Muuda parooli";
$l_opt_curpass = "Praegune parool:";
$l_opt_newpass = "Uus parool:";
$l_opt_newpagain = "Uus parool (uuesti):";
$l_opt_userint = "Kasutajaliides";
$l_opt_usenew = "Kasuta t&auml;ielikku kasutajaliidest?";
$l_opt_lang = "Keel";
$l_opt_select = "Vali &uuml;ks:";
$l_opt_enabled = "Lubatud";
$l_opt_save = "Salvesta";

// Option2.php

$l_opt2_title = "Seadete salvestamine";
$l_opt2_passunchanged = "Parool j&auml;eti muutmata.<BR><BR>";
$l_opt2_srcpassfalse = "Praegune parool ei olnud &otilde;ige. Parool j&auml;eti muutmata.<BR><BR>";
$l_opt2_newpassnomatch = "Uued paroolid ei olnud &uuml;hesugused. Parool j&auml;eti muutmata.<BR><BR>";
$l_opt2_passchanged = "Parool muudetud.<BR><BR>";
$l_opt2_passchangeerr = "Viga parooli muutmisel<BR><BR>";
$l_opt2_userintup = "Kasutajaliidese seaded uuendatud.<BR><BR>";
$l_opt2_userintfail = "Kasutajaliidese seadete muutmine eba&otilde;nnestus.<BR><BR>";
$l_opt2_chlang = "Kasutusele v&otilde;eti [lang] keel.<p>";
$l_opt2_dhtmlup = "D&uuml;naamilise html-i seaded uuendatud.<BR><BR>";
$l_opt2_dhtmlfail = "D&uuml;naamilise html-i seadete muutmine eba&otilde;nnestus.<BR><BR>";

// Presets.php

$l_pre_title = "Avakosmose kiirvalikud";
$l_pre_exceed = "Kiirvalik [preset] &uuml;letab universumi maksimaalset suurust [sector_max]. Kiirvalikuid ei salvestatud.<BR><BR>";
$l_pre_set = "Kiirvalikuks number 1 m&auml;&auml;rati [preset1], kiirvalikuks number 2 m&auml;&auml;rati [preset2] ja kiirvalikuks number 3 m&auml;&auml;rati [preset3].<BR><BR>";
$l_pre_save = "Salvesta";

// Mailto.php

$l_mt_title = "Teate saatmine";
$l_mt_from = "Saatja:";
$l_mt_subject = "Teema:";
$l_mt_message = "Teade";
$l_mt_sent = "Teade saadetud";
$l_mt_send = "Saada";

// sector_fighters.php
$l_sf_attacking = "Sektori kaitse h&auml;vitajad r&uuml;ndasid Sind!<BR>";
$l_sf_destfight = "Su laserid purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_destfightb = "Su laserid purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_torphit = "Torpeedod tulistati v&auml;lja:";
$l_sf_destfightt = "Su torpeedod purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_fighthit = "H&auml;vitajad r&uuml;ndasid:";
$l_sf_destfightall = "Sa purustasid k&otilde;ik h&auml;vitajad.<BR>";
$l_sf_destfightt2 = "Sa purustasid [lost] h&auml;vitajat.<BR>";
$l_sf_lostfight = "Sa kaotasid k&otilde;ik h&auml;vitajad.<BR>";
$l_sf_lostfight2 = "Sa kaotasid [lost] h&auml;vitajat.<BR>";
$l_sf_armorbreach = "Su soomus on purustatud!<BR>";
$l_sf_armorbreach2 = "Su soomus sai [lost] punkti ulatuses vigastada.<BR>";
$l_sf_sendlog = "[player] purustas [lost] sektori kaitse h&auml;vitajat sektoris [sector].";
$l_sf_lreport = "Sa kaotasid [armor] soomusepunkti, [fighters] h&auml;vitajat ja kasutasid &auml;ra [torps] torpeedot.<BR><BR>";
$l_sf_shipdestroyed = "<B>Su laev on purustatud!</B><BR><BR>";
$l_sf_sendlog2 = "Sektori kaitse h&auml;vitajad purustasid m&auml;ngija [player] sektoris [sector].";
$l_sf_escape = "&Otilde;nneks oli Sul p&auml;&auml;stekapsel!<BR><BR>";

// Zone names

$l_zname[1] = "Kaardistamata kosmos";
$l_zname[2] = "F&ouml;deratsiooni ala";
$l_zname[3] = "Vabakaubanduspiirkond";
$l_zname[4] = "S&otilde;jatsoon";

// ADDITION TO warpedit2.php

$l_warp_cantsame = "Sa ei saa luua varp-koridori, mille algus- ja l&otilde;ppsektor on samad.";

// Bounty
$l_by_title = "Pearahad";
$l_by_noturn = "Sul peab olema v&auml;hemalt &uuml;ks k&auml;ik, et pearaha v&auml;lja panna v&otilde;i muuta.";
$l_by_amount = "Pearaha summa";
$l_by_place = "Pane v&auml;lja";
$l_by_nobounties = "&Uuml;htegi pearaha ei ole v&auml;lja pandud.";
$l_by_bountyon = "Kelle eest"; // Leia parem t6lge, kui oskad
$l_by_placedby = "V&auml;ljapanija";
$l_by_thefeds  = "F&ouml;deratsioon";
$l_by_cancel   = "T&uuml;hista";
$l_by_yourself = "Sa ei saa enda eest pearaha v&auml;lja panna!";
$l_by_notenough = "Sul ei ole piisavalt raha, et sellist pearaha v&auml;lja panna.";
$l_by_toomuch   = "Sa ei saa sellist pearaha v&auml;lja panna. Maksimaalne lubatud pearaha suurus on [percent] protsenti Su impeeriumi v&auml;&auml;rtusest";
$l_by_zeroamount = "Pearaha summa peab olema suurem kui 0.";
$l_by_placed     = "Pearaha v&auml;lja pandud.";
$l_by_nobounty = "Seda pearaha ei ole enam.";
$l_by_notyours = "Seda pearaha ei ole Sina v&auml;lja pannud.";
$l_by_canceled = "Pearaha on t&uuml;histatud.";
$l_by_action   = "Tegevus";
$l_by_placebounty = "Pane v&auml;lja v&otilde;i vaata pearahasid.";
$l_by_moredetails = "Kliki nimel, et rohkem teada saada.";
$l_by_fedbounty = "Kui Sa seda m&auml;ngijat r&uuml;ndad, paneb F&ouml;deratsioon Su laeva eest pearaha v&auml;lja.";
$l_by_fedbounty2 = "F&ouml;deratsioon ei luba palju v&auml;iksemate laevade r&uuml;ndamist. Su laeva eest pandi pearaha v&auml;lja.";
$l_by_notexists = "Sellist m&auml;ngijat ei ole.";
$l_by_destroyed = "Sa ei saa panna pearaha v&auml;lja laeva eest, mis on purustatud.";
$l_log_text[LOG_BOUNTY_CLAIMED] = "Sa said k&auml;tte [amount] raha suuruse pearaha, kuna purustasid m&auml;ngija [bounty_on] laeva. Pearaha oli v&auml;lja pannud [placed_by].";
$l_log_title[LOG_BOUNTY_CLAIMED] = "Pearaha k&auml;tte saadud";
$l_log_text[LOG_BOUNTY_PAID] = "Su pearaha m&auml;ngija [bounty_on] eest on summas [amount] v&auml;lja makstud.";
$l_log_title[LOG_BOUNTY_PAID] = "Pearaha v&auml;lja makstud";
$l_log_text[LOG_BOUNTY_CANCELLED] = "Su pearaha m&auml;ngija [bounty_on] eest summas [amount] raha on Sulle tagastatud.";
$l_log_title[LOG_BOUNTY_CANCELLED] = "Pearaha tagasi makstud";
$l_log_text[LOG_SPACE_PLAGUE] = "Su planeeti [name] sektoris [sector] tabas kosmiline katk. [percentage] protsenti kolonistidest hukkus.";
$l_log_title[LOG_SPACE_PLAGUE] = "Kosmiline katk!";
$l_log_text[LOG_PLASMA_STORM] = "Su planeeti [name] sektoris [sector] tabas pasmatorm. Selle tagaj&auml;rjel h&auml;vis kogu varutud energia.";
$l_log_title[LOG_PLASMA_STORM] = "Plasmatorm!";
$l_log_text[LOG_BOUNTY_FEDBOUNTY] = "F&ouml;deratsioon on Su laeva eest [amount] suuruse pearaha v&auml;lja pannud.";
$l_log_title[LOG_BOUNTY_FEDBOUNTY] = "F&ouml;deratsiooni pearaha!";
$l_new_pwis = "Su parool on";
$l_planet2_sector = "Sa ei ole samas sektoris, kus planeet.";
$l_planet_destroyplanet = "H&auml;vita planeet";
$l_planet_warning = " See purustab planeedi t&auml;ielikult!";
$l_planet_confirm = "Kas Sa t&otilde;esti soovid selle planeedi h&auml;vitada?";
$l_port_bounty = "Sind ei lasta keskjaama, kui Sinu laeva eest on F&ouml;deratsioon pearaha v&auml;lja pannud.<BR>";
$l_port_bounty2 = "Vajuta <a href=\"port.php?pay=1\">siia</a> et maksta [amount] raha suurune pearaha.";
$l_port_btynotenough = "Sul ei ole piisavalt raha, et maksta [amount] suurust pearaha.<BR>";
$l_port_bountypaid = "Sa maksid pearaha v&auml;lja. Vajuta <a href=\"port.php\">siia</a> et j&auml;tkata.<BR>";
$l_port_loannotrade = "IGB lukustas Su laeva konto, kuna Sa oled laenu tagasi maksmisega hiljaks j&auml;&auml;nud. Sa ei saa enne keskjaamas kaubelda, kui oled oma laenu tagasi maksnud.";
$l_team_notyours = "Et kedagi kutsuda, pead Sa ise liidus olema.";
$l_team_leavefirst = "Sa pead enne &uuml;hest liidust lahkuma kui teisega &uuml;hineda saad.";


$l_tdr_engageagain = "Vajuta <A HREF=\"traderoute.php?engage=[tdr_engage]\">siia</A> et uuesti kaubelda, v&otilde;i siia, et kaubelda <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=5\">viis</A>,  <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=10\">k&uuml;mme</A> v&otilde;i <A HREF=\"traderoute.php?engage=[tdr_engage]&tr_repeat=50\">viisk&uuml;mmend</A> korda.<p>";
$l_scan_bounty = "Selle laeva eest on kokku [amount] raha suurune pearaha v&auml;lja pandud.";
$l_scan_fedbounty = "Selle laeva eest on F&ouml;deratsioon pearaha v&auml;lja pannud.";
$l_by_nofedbounty = "Selle m&auml;ngija r&uuml;ndamise eest <B>EI</B> pane F&ouml;deratsioon Su laeva eest pearaha v&auml;lja.";

//Fig Drops

$l_sofa = "Orbitaalne h&auml;vitajate r&uuml;nnak";
$l_bombsaway = "Sa saatsid oma h&auml;vitajad planeedi poole teele, j&auml;&auml;des ise ohutusse kaugusesse.";
$l_bigfigs = "Su hiiglaslik laev andis planeedi kaitsjatele juba kaugelt m&auml;rku, et Sa oled tulekul ning v&otilde;imaldas neil ettevalmistustega alustada. Su h&auml;vitajad ei ole seega v&auml;ga efektiivsed.";
$l_bigbeams = "Planeedi kohal toimub metsik laserkiirte m&ouml;ll. Su h&auml;vitajad ei j&otilde;udnud ilmselt isegi mitte planeedi atmosf&auml;&auml;rini.";
$l_bigtorps = "Planeedi atmosf&auml;&auml;ri &uuml;lakihtides toimuvad v&otilde;imsad torpeedoplahvatused. Su h&auml;vitajad ei j&otilde;udnud ilmselt midagi r&uuml;nnata.";
$l_strafesuccess = "Paistab, et osa Su h&auml;vitajatest j&otilde;udis planeedini v&auml;lja, kahjuks ei suuda Sa aga &ouml;elda kui paljud just.";
$l_log_text[LOG_PLANET_BOMBED] = "Su planeeti [planet_name] sektoris [sector] r&uuml;ndasid m&auml;ngija [name] h&auml;vitjad. Sa kasutasid &auml;ra [beams] &uuml;hikut energiat ja [torps] torpeedot, et ennast kaitsta.  Sa kaotasid [figs] h&auml;vitajat.";
$l_log_title[LOG_PLANET_BOMBED] = "<font color=red>Planeeti pommitati!</font>";
$l_lssd = "Viimati n&auml;htud laeva skanner";
$l_lss = "Viimati n&auml;htud laev selles sektoris";
$l_map = "Galaktika kaart";
$l_igb_errnobase = "IGB ei saa kanda raha planeedile, millel ei ole baasi.";


//Changed messages
$l_log_text[LOG_TOW] = "Su laev t&otilde;steti sektorist [sector] sektorisse [newsector], sest Su laeva keskmine tehniline tase &uuml;letas lubatud v&auml;&auml;rtuse [hull].";

//Footer text
$l_footer_one_player_on = "Sisse on loginud 1 m&auml;ngija.";
$l_footer_players_on_1 = "Sisse on loginud";
$l_footer_players_on_2 = "m&auml;ngijat.";
$l_footer_until_update = "sekundit on j&auml;&auml;nud j&auml;rgmise uuendamiseni.";

//Ship officer insignia
$l_insignia[0] = "Reamees";
$l_insignia[1] = "Kapral";
$l_insignia[2] = "Nooremseersant";
$l_insignia[3] = "Seersant";
$l_insignia[4] = "Vanemseersant";
$l_insignia[5] = "Nooremveebel";
$l_insignia[6] = "Veebel";
$l_insignia[7] = "Vanemveebel";
$l_insignia[8] = "&Uuml;lemveebel";
$l_insignia[9] = "Lipnik";
$l_insignia[10] = "Nooremleitnant";
$l_insignia[11] = "Leitnant";
$l_insignia[12] = "Kapten";
$l_insignia[13] = "Major";
$l_insignia[14] = "Kolonelleitnant";
$l_insignia[15] = "Kolonel";
$l_insignia[16] = "Brigaadikindral";
$l_insignia[17] = "Kindralmajor";
$l_insignia[18] = "Kindralleitnant";
$l_insignia[19] = "Kindral";

// shipyard.php

$l_shipyard_title = "Laevatehas";
$l_planet = "Planeet";

$l_cmb_needfighters = "Sul peab olema v&auml;hemalt 1 h&auml;vitaja.";

// planet.php
$l_log_text[LOG_PLANET_YOUR_CAPTURED] = "Su planeet [planet_name] sektoris [sector] alistati ja h&otilde;ivati nurjatu m&auml;ngija [name] poolt.";
$l_log_title[LOG_PLANET_YOUR_CAPTURED] = "<font color=red>Planeet h&otilde;ivatud!</font>";

?>